/**
 * Latency Routes
 *
 * Exposes latency alert information generated by the latency monitor.
 *
 * @module routes/latency
 */

import { Router, Request, Response } from 'express';
import { sendSuccess } from '../middleware/responseWrapper';
import { latencyMonitor, LatencyOperation } from '../services/latencyMonitor';

const router = Router();

router.get('/latency-alerts', (req: Request, res: Response) => {
  const { collection, operation, since } = req.query;

  const sinceTimestamp = since ? Date.parse(String(since)) : undefined;
  const parsedOperation = operation && typeof operation === 'string'
    ? (operation as LatencyOperation)
    : undefined;

  const alerts = latencyMonitor.getAlerts({
    collection: typeof collection === 'string' ? collection : undefined,
    operation: parsedOperation,
    since: Number.isFinite(sinceTimestamp) ? sinceTimestamp : undefined,
  });

  return sendSuccess(res, {
    alerts,
    config: latencyMonitor.getConfig(),
  });
});

export default router;
