/**
 * AI Agents Directory - Metadata Only (GENERATED)
 *
 * This file contains only agent metadata WITHOUT full file content.
 * Full agent content is loaded on-demand via loadAgentContent().
 *
 * Size Impact:
 * - Full data: ~642KB
 * - Metadata only: ~67KB
 * - Reduction: 89.6%
 *
 * ⚠️  DO NOT EDIT MANUALLY
 * Generated by: scripts/generate-agents-metadata.mjs
 * Generated at: 2025-11-08T19:50:20.279Z
 */

export const AGENT_CATALOG_SCHEMA_VERSION = "1.1.0";

export type AgentCategory =
  | "Arquitetura & Plataforma"
  | "Backend & Serviços"
  | "Frontend & UX"
  | "Dados & Analytics"
  | "IA, ML & RAG"
  | "Documentação & Conteúdo"
  | "Pesquisa & Estratégia"
  | "QA & Observabilidade"
  | "MCP & Automação";

export interface AgentMetadata {
  id: string;
  name: string;
  category: AgentCategory;
  capabilities: string;
  usage: string;
  example: string;
  shortExample?: string;
  outputType: string;
  tags: string[];
  filePath: string;
  // fileContent is NOT included - loaded on-demand
}

export const AGENT_CATEGORY_ORDER: AgentCategory[] = [
  "Arquitetura & Plataforma",
  "Backend & Serviços",
  "Frontend & UX",
  "Dados & Analytics",
  "IA, ML & RAG",
  "Documentação & Conteúdo",
  "Pesquisa & Estratégia",
  "QA & Observabilidade",
  "MCP & Automação",
];

/**
 * Lazy-loads full agent content on-demand
 * @param agentId - The agent ID to load content for
 * @returns Promise with full agent data including fileContent
 */
export async function loadAgentContent(
  agentId: string,
): Promise<{ fileContent: string }> {
  // Dynamic import of full data only when needed
  const module = await import("./aiAgentsDirectory");
  const agent = module.AI_AGENTS_DIRECTORY.find((a: any) => a.id === agentId);

  if (!agent?.fileContent) {
    throw new Error(`Agent content not found for: ${agentId}`);
  }

  return { fileContent: agent.fileContent };
}

// Metadata-only agents array (fileContent stripped)
export const AI_AGENTS_METADATA: AgentMetadata[] = [
  {
    id: "architect-reviewer",
    name: "@architect-reviewer",
    category: "Arquitetura & Plataforma",
    capabilities:
      "revisa aderência a SOLID, camadas limpas e padrões arquiteturais",
    usage:
      "ativar em PRs estruturais, novos serviços ou refatorações que precisem manter a Clean Architecture.",
    example:
      "Rodar antes de aprovar o PR que refatorou `backend/api/workspace/src/core/orders` para garantir que domain, application e infra continuem desacoplados.",
    shortExample: "`@architect-reviewer revise backend/api/workspace`",
    outputType: "Relatório técnico com recomendações arquiteturais.",
    tags: [
      "arquitetura",
      "plataforma",
      "architect-reviewer",
      "revisa-aderencia",
      "camadas-limpas",
    ],
    filePath: "/.claude/agents/architect-reviewer.md",
  },
  {
    id: "architecture-modernizer",
    name: "@architecture-modernizer",
    category: "Arquitetura & Plataforma",
    capabilities:
      "conduz modernização arquitetural, migra monólitos, desenha microservices e eventos",
    usage:
      "quando avaliarmos evolução de bounded contexts ou escalabilidade dos domínios de trading.",
    example:
      "Aplicar ao definir o blueprint que separa o ingestion service do módulo `backend/api/workspace` e publica eventos em `docs/content/reference/adrs/ADR-017-microservices.mdx`.",
    shortExample:
      "`@architecture-modernizer analise migração para microservices`",
    outputType: "Relatório técnico com recomendações arquiteturais.",
    tags: [
      "arquitetura",
      "plataforma",
      "architecture-modernizer",
      "conduz-modernizacao",
      "migra-monolitos",
    ],
    filePath: "/.claude/agents/architecture-modernizer.md",
  },
  {
    id: "backend-architect",
    name: "@backend-architect",
    category: "Arquitetura & Plataforma",
    capabilities:
      "projeta APIs, contratos REST e limites de microserviços com foco em desempenho",
    usage:
      "útil ao definir novos serviços da camada `backend/api` ou revisar integrações TP Capital.",
    example:
      "Usar quando desenhamos o endpoint `/signals/stream` em `backend/api/telegram-gateway/src/routes/signals.ts`, validando DTOs e limites de agregados.",
    shortExample: "`@backend-architect projete API para sinais de trading`",
    outputType: "Relatório técnico com recomendações arquiteturais.",
    tags: [
      "arquitetura",
      "plataforma",
      "backend-architect",
      "projeta-apis",
      "contratos-rest",
    ],
    filePath: "/.claude/agents/backend-architect.md",
  },
  {
    id: "cloud-architect",
    name: "@cloud-architect",
    category: "Arquitetura & Plataforma",
    capabilities:
      "estrutura infraestrutura em nuvem, IaC e otimização de custos",
    usage:
      "acionado para comparar estratégia on-premise vs. híbrida ou validar pipelines Terraform usados no laboratório.",
    example:
      "Acionar ao revisar o desenho do cluster híbrido descrito em `tools/compose/docker-compose.apps.yml` e compará-lo com o plano Terraform arquivado em `infrastructure/README.md`.",
    shortExample: "`@cloud-architect compare on-premise vs cloud híbrida`",
    outputType: "Relatório técnico com recomendações arquiteturais.",
    tags: [
      "arquitetura",
      "plataforma",
      "cloud-architect",
      "estrutura-infraestrutura",
      "iac-e",
    ],
    filePath: "/.claude/agents/cloud-architect.md",
  },
  {
    id: "cloud-migration-specialist",
    name: "@cloud-migration-specialist",
    category: "Arquitetura & Plataforma",
    capabilities: "planeja migrações para cloud, containerização e serverless",
    usage:
      "avaliar viabilidade de portar componentes auxiliares (monitoramento, documentação) para ambientes cloud sem afetar o core on-premise.",
    example:
      "Ex.: avaliar migração do stack de documentação (`docs` + `documentation-api`) para uma VPC separada descrita no runbook `docs/content/tools/runtime/dotnet/overview.mdx`.",
    shortExample:
      "`@cloud-migration-specialist planeje migração do monitoring`",
    outputType: "Relatório técnico com recomendações arquiteturais.",
    tags: [
      "arquitetura",
      "plataforma",
      "cloud-migration-specialist",
      "planeja-migracoes",
      "containerizacao-e",
    ],
    filePath: "/.claude/agents/cloud-migration-specialist.md",
  },
  {
    id: "deployment-engineer",
    name: "@deployment-engineer",
    category: "Arquitetura & Plataforma",
    capabilities:
      "automatiza pipelines CI/CD, versionamento e estratégias de deploy",
    usage:
      "ao criar fluxos GitHub Actions ou ajustar scripts `scripts/agents` e `tools/compose` para releases confiáveis.",
    example:
      "Executar quando criamos um pipeline GitHub Actions para `frontend/dashboard` baseado no script `scripts/ci/dashboard-build.yml` garantindo promoções automatizadas.",
    shortExample: "`@deployment-engineer crie pipeline CI/CD para dashboard`",
    outputType: "Relatório técnico com recomendações arquiteturais.",
    tags: [
      "arquitetura",
      "plataforma",
      "deployment-engineer",
      "automatiza-pipelines",
      "versionamento-e",
    ],
    filePath: "/.claude/agents/deployment-engineer.md",
  },
  {
    id: "devops-engineer",
    name: "@devops-engineer",
    category: "Arquitetura & Plataforma",
    capabilities: "integra infra, observabilidade, segurança e automação",
    usage:
      "quando precisarmos harmonizar pipelines, secrets centralizados e monitoramento de serviços dockerizados.",
    example:
      "Chamar ao revisar o playbook `scripts/maintenance/health-check-all.sh`, unificando secrets do `.env` único com as stacks dockerizadas.",
    shortExample: "`@devops-engineer harmonize secrets e monitoring`",
    outputType: "Relatório técnico com recomendações arquiteturais.",
    tags: [
      "arquitetura",
      "plataforma",
      "devops-engineer",
      "integra-infra",
      "observabilidade",
    ],
    filePath: "/.claude/agents/devops-engineer.md",
  },
  {
    id: "devops-troubleshooter",
    name: "@devops-troubleshooter",
    category: "Arquitetura & Plataforma",
    capabilities:
      "faz triagem de incidentes, leitura de logs e correção pós-deploy",
    usage:
      "indicado para investigar falhas em `tools/compose` ou degradações nas APIs TP Capital/Documentation.",
    example:
      "Usar ao investigar queda do serviço `tp-capital` olhando `logs/containers/tp-capital.log` e correlacionando com `docker compose ps`.",
    shortExample: "`@devops-troubleshooter investigue falha no TP Capital`",
    outputType: "Relatório técnico com recomendações arquiteturais.",
    tags: [
      "arquitetura",
      "plataforma",
      "devops-troubleshooter",
      "faz-triagem",
      "leitura-de",
    ],
    filePath: "/.claude/agents/devops-troubleshooter.md",
  },
  {
    id: "docker-health-optimizer",
    name: "@docker-health-optimizer",
    category: "Arquitetura & Plataforma",
    capabilities:
      "audita stacks Docker, saúde do daemon e performance de containers",
    usage:
      "essencial para validar `scripts/docker/start-stacks.sh`, consumo de recursos e aderência ao .env único.",
    example:
      "Acionar após atualizar `tools/compose/docker-compose.apps.yml` para conferir limites de CPU/RAM e liveness de `workspace-api` via `docker stats`.",
    shortExample: "`@docker-health-optimizer audite docker-compose.apps.yml`",
    outputType: "Relatório técnico com recomendações arquiteturais.",
    tags: [
      "arquitetura",
      "plataforma",
      "docker-health-optimizer",
      "audita-stacks",
      "saude-do",
    ],
    filePath: "/.claude/agents/docker-health-optimizer.md",
  },
  {
    id: "legacy-modernizer",
    name: "@legacy-modernizer",
    category: "Arquitetura & Plataforma",
    capabilities:
      "moderniza código legado, aplica refactors incrementais e padrões atuais",
    usage:
      "útil ao migrar módulos antigos de execução nativa ProfitDLL para services modernos ou TypeScript.",
    example:
      "Rodar quando migramos scripts antigos de ProfitDLL em `backend/data/legacy-scripts/` para um módulo Node documentado em `docs/content/tools/trading/profitdll/overview.mdx`.",
    shortExample: "`@legacy-modernizer modernize ProfitDLL integration`",
    outputType: "Relatório técnico com recomendações arquiteturais.",
    tags: [
      "arquitetura",
      "plataforma",
      "legacy-modernizer",
      "moderniza-codigo",
      "aplica-refactors",
    ],
    filePath: "/.claude/agents/legacy-modernizer.md",
  },
  {
    id: "monitoring-specialist",
    name: "@monitoring-specialist",
    category: "Arquitetura & Plataforma",
    capabilities:
      "desenha estratégias de observabilidade, SLIs/SLOs e integra alertas",
    usage:
      "aplicar aos dashboards Prometheus/Grafana em `tools/monitoring` e garantir cobertura dos serviços críticos.",
    example:
      "Usar ao ajustar os dashboards Grafana em `tools/monitoring/grafana/provisioning/dashboards`, garantindo métricas para latência de sinais.",
    shortExample: "`@monitoring-specialist desenhe SLIs para APIs`",
    outputType: "Relatório técnico com recomendações arquiteturais.",
    tags: [
      "arquitetura",
      "plataforma",
      "monitoring-specialist",
      "desenha-estrategias",
      "slis-slos-e",
    ],
    filePath: "/.claude/agents/monitoring-specialist.md",
  },
  {
    id: "network-engineer",
    name: "@network-engineer",
    category: "Arquitetura & Plataforma",
    capabilities: "modela redes, segurança, roteamento e troubleshooting",
    usage:
      "quando configurarmos redes bridge/policies no Docker Compose ou integrações com bolsas externas.",
    example:
      "Acionado ao revisar regras de firewall do túnel que expõe `telegram-gateway` descritas em `docs/content/tools/security-config/networking.mdx`.",
    shortExample: "`@network-engineer configure redes Docker bridge`",
    outputType: "Relatório técnico com recomendações arquiteturais.",
    tags: [
      "arquitetura",
      "plataforma",
      "network-engineer",
      "modela-redes",
      "seguranca",
    ],
    filePath: "/.claude/agents/network-engineer.md",
  },
  {
    id: "nextjs-architecture-expert",
    name: "@nextjs-architecture-expert",
    category: "Arquitetura & Plataforma",
    capabilities: "define arquitetura Next.js com SSR/SSG e otimização",
    usage:
      "apoiar migrações futuras do dashboard Vite para frameworks híbridos ou páginas estáticas de documentação.",
    example:
      "Aplicar quando desenhamos o novo portal de relatórios em Next.js dentro de `frontend/apps/reports`, validando roteamento híbrido e data fetching.",
    shortExample: "`@nextjs-architecture-expert migre dashboard para Next.js`",
    outputType: "Relatório técnico com recomendações arquiteturais.",
    tags: [
      "arquitetura",
      "plataforma",
      "nextjs-architecture-expert",
      "define-arquitetura",
    ],
    filePath: "/.claude/agents/nextjs-architecture-expert.md",
  },
  {
    id: "api-documenter",
    name: "@api-documenter",
    category: "Backend & Serviços",
    capabilities: "gera especificações OpenAPI e SDKs",
    usage:
      "para manter `tools/openspec` e documentação das APIs Workspace/Documentation/Tp Capital sincronizadas.",
    example:
      "Invocar ao escrever o contrato atualizado do endpoint `/tp-capital/orders` em `docs/content/api/reference/tp-capital.mdx` a partir do código real.",
    shortExample: "`@api-documenter gere OpenAPI para Workspace API`",
    outputType:
      "Plano de implementação com endpoints, fluxos e exemplos de código.",
    tags: ["backend", "servicos", "api-documenter", "gera-especificacoes"],
    filePath: "/.claude/agents/api-documenter.md",
  },
  {
    id: "c-pro",
    name: "@c-pro",
    category: "Backend & Serviços",
    capabilities: "domina C de baixo nível, ponteiros e otimização",
    usage:
      "quando lidarmos com integrações ProfitDLL ou componentes nativos de baixa latência.",
    example:
      "Usar quando precisamos otimizar o coletor ProfitDLL em `backend/data/profitdll/*.c`, garantindo buffers e FFI corretos.",
    shortExample: "`@c-pro otimize callback ProfitDLL`",
    outputType:
      "Plano de implementação com endpoints, fluxos e exemplos de código.",
    tags: ["backend", "servicos", "c-pro", "domina-c", "ponteiros-e"],
    filePath: "/.claude/agents/c-pro.md",
  },
  {
    id: "dependency-manager",
    name: "@dependency-manager",
    category: "Backend & Serviços",
    capabilities: "saneia dependências, versões sem conflitos e licenças",
    usage:
      "limpar `package.json` múltiplos, evitar duplicidades e garantir builds determinísticos.",
    example:
      "Rodar antes de atualizar `package.json` e `pnpm-lock.yaml` dos serviços `backend/api` para sugerir bump seguro e auditoria de licenças.",
    shortExample: "`@dependency-manager limpe package.json duplicados`",
    outputType:
      "Plano de implementação com endpoints, fluxos e exemplos de código.",
    tags: [
      "backend",
      "servicos",
      "dependency-manager",
      "saneia-dependencias",
      "versoes-sem",
    ],
    filePath: "/.claude/agents/dependency-manager.md",
  },
  {
    id: "fullstack-developer",
    name: "@fullstack-developer",
    category: "Backend & Serviços",
    capabilities: "integra frontend/backend com padrões modernos",
    usage:
      "suporte quando uma feature exige coordenação simultânea entre React dashboard e APIs Express.",
    example:
      "Aplicar ao implementar a tela de orquestração em `frontend/dashboard/src/components/pages/LauncherPage.tsx` junto com o endpoint `backend/api/documentation-api/src/routes/launcher.ts`.",
    shortExample: "`@fullstack-developer implemente feature de alertas`",
    outputType:
      "Plano de implementação com endpoints, fluxos e exemplos de código.",
    tags: [
      "backend",
      "servicos",
      "fullstack-developer",
      "integra-frontend-backend",
    ],
    filePath: "/.claude/agents/fullstack-developer.md",
  },
  {
    id: "graphql-architect",
    name: "@graphql-architect",
    category: "Backend & Serviços",
    capabilities: "modela esquemas GraphQL, resolvers e federations",
    usage:
      "avaliar adoção de GraphQL em agregação de dados do RAG ou dashboards analíticos.",
    example:
      "Usar quando definimos o schema unificado em `backend/api/workspace/graphql/schema.graphql` que alimenta o dashboard.",
    shortExample: "`@graphql-architect modele schema para dados RAG`",
    outputType:
      "Plano de implementação com endpoints, fluxos e exemplos de código.",
    tags: [
      "backend",
      "servicos",
      "graphql-architect",
      "modela-esquemas",
      "resolvers-e",
    ],
    filePath: "/.claude/agents/graphql-architect.md",
  },
  {
    id: "graphql-performance-optimizer",
    name: "@graphql-performance-optimizer",
    category: "Backend & Serviços",
    capabilities: "identifica gargalos e caching em operações GraphQL",
    usage:
      "otimizar consultas complexas caso GraphQL seja adotado para dados de mercado.",
    example:
      "Acionar ao investigar resolvers lentos do schema localizado em `backend/api/workspace/graphql/resolvers/positions.ts`, propondo dataloaders.",
    shortExample: "`@graphql-performance-optimizer otimize queries de mercado`",
    outputType:
      "Plano de implementação com endpoints, fluxos e exemplos de código.",
    tags: [
      "backend",
      "servicos",
      "graphql-performance-optimizer",
      "identifica-gargalos",
    ],
    filePath: "/.claude/agents/graphql-performance-optimizer.md",
  },
  {
    id: "graphql-security-specialist",
    name: "@graphql-security-specialist",
    category: "Backend & Serviços",
    capabilities:
      "hardening de APIs GraphQL, controle de introspecção e rate limiting",
    usage:
      "garantir que endpoints experimentais de RAG não exponham dados sensíveis.",
    example:
      "Rodar enquanto auditamos o servidor Apollo descrito em `backend/api/workspace/src/graphql/server.ts` contra ataques de query batching.",
    shortExample: "`@graphql-security-specialist hardening endpoints RAG`",
    outputType:
      "Plano de implementação com endpoints, fluxos e exemplos de código.",
    tags: [
      "backend",
      "servicos",
      "graphql-security-specialist",
      "hardening-de",
      "controle-de",
    ],
    filePath: "/.claude/agents/graphql-security-specialist.md",
  },
  {
    id: "javascript-pro",
    name: "@javascript-pro",
    category: "Backend & Serviços",
    capabilities:
      "resolve desafios avançados em JS, desempenho e interoperabilidade",
    usage:
      "tarefas críticas em Node ou scripts de automação que exigem domínio profundo da linguagem.",
    example:
      "Aplicar ao refatorar utilitários em `frontend/dashboard/src/utils/date.ts`, garantindo tipagens e ergonomia modernas.",
    shortExample: "`@javascript-pro resolva async/await complexo`",
    outputType:
      "Plano de implementação com endpoints, fluxos e exemplos de código.",
    tags: [
      "backend",
      "servicos",
      "javascript-pro",
      "resolve-desafios",
      "desempenho-e",
    ],
    filePath: "/.claude/agents/javascript-pro.md",
  },
  {
    id: "python-pro",
    name: "@python-pro",
    category: "Backend & Serviços",
    capabilities:
      "escreve código Python otimizado, integra libs científicas e CLI",
    usage:
      "scripts auxiliares de dados, protótipos de estratégias ou automações de legado.",
    example:
      "Usar quando ajustamos automações em `scripts/agents/*.py` ou ETLs rápidos dentro de `backend/data/pipelines`, garantindo virtualenvs e linters.",
    shortExample: "`@python-pro crie script ML para previsão`",
    outputType:
      "Plano de implementação com endpoints, fluxos e exemplos de código.",
    tags: [
      "backend",
      "servicos",
      "python-pro",
      "escreve-codigo",
      "integra-libs",
    ],
    filePath: "/.claude/agents/python-pro.md",
  },
  {
    id: "cli-ui-designer",
    name: "@cli-ui-designer",
    category: "Frontend & UX",
    capabilities: "traz estética de terminais para interfaces web",
    usage:
      "criar experiências CLI-like no dashboard ou painéis internos para equipes de operações.",
    example:
      "Invocar ao desenhar o layout inspirado em terminal para o painel `Toolbox → Scripts`, prototipado em `frontend/dashboard/src/components/terminal/`.",
    shortExample: "`@cli-ui-designer crie painel CLI-style`",
    outputType:
      "Guia visual ou recomendações de UI/UX com referências de componentes.",
    tags: ["frontend", "ux", "cli-ui-designer", "traz-estetica"],
    filePath: "/.claude/agents/cli-ui-designer.md",
  },
  {
    id: "frontend-developer",
    name: "@frontend-developer",
    category: "Frontend & UX",
    capabilities: "implementa features em React/Vite com boas práticas",
    usage: "desenvolvimento contínuo do dashboard (`frontend/dashboard`).",
    example:
      "Ex.: implementar o componente `CatalogFilters` em `frontend/dashboard/src/components/catalog/` consumindo TanStack Query.",
    shortExample: "`@frontend-developer implemente catálogo unificado`",
    outputType:
      "Guia visual ou recomendações de UI/UX com referências de componentes.",
    tags: ["frontend", "ux", "frontend-developer", "implementa-features"],
    filePath: "/.claude/agents/frontend-developer.md",
  },
  {
    id: "mobile-developer",
    name: "@mobile-developer",
    category: "Frontend & UX",
    capabilities: "cria apps móveis híbridos ou nativos",
    usage: "avaliar clientes móveis para alertas ou monitoramento de posições.",
    example:
      "Rodar ao criar um proof-of-concept do app React Native que consome a API `backend/api/workspace`, com build descrito em `docs/content/mobile/alerts.mdx`.",
    shortExample: "`@mobile-developer crie app React Native para alertas`",
    outputType:
      "Guia visual ou recomendações de UI/UX com referências de componentes.",
    tags: ["frontend", "ux", "mobile-developer", "cria-apps"],
    filePath: "/.claude/agents/mobile-developer.md",
  },
  {
    id: "react-performance-optimization",
    name: "@react-performance-optimization",
    category: "Frontend & UX",
    capabilities:
      "recomenda otimizações de bundling, memoização e lazy loading",
    usage:
      "reduzir tempo de carregamento das páginas de busca híbrida e coleções.",
    example:
      "Aplicar ao revisar o bundle `frontend/dashboard/dist/assets/agents-catalog.js` usando `npm run analyze:bundle` para sugerir code-splitting.",
    shortExample: "`@react-performance-optimization otimize bundle size`",
    outputType:
      "Guia visual ou recomendações de UI/UX com referências de componentes.",
    tags: [
      "frontend",
      "ux",
      "react-performance-optimization",
      "recomenda-otimizacoes",
      "memoizacao-e",
    ],
    filePath: "/.claude/agents/react-performance-optimization.md",
  },
  {
    id: "react-performance-optimizer",
    name: "@react-performance-optimizer",
    category: "Frontend & UX",
    capabilities: "diagnostica gargalos reais de renderização",
    usage:
      "acompanhar componentes pesados (ex. `CollectionFilesTable`) quando métricas Web Vitals apontarem lentidão.",
    example:
      "Usar durante o profiling do componente `AIAgentsDirectory` com React DevTools Profiler conectando no Vite dev server.",
    shortExample: "`@react-performance-optimizer profile CollectionFilesTable`",
    outputType:
      "Guia visual ou recomendações de UI/UX com referências de componentes.",
    tags: [
      "frontend",
      "ux",
      "react-performance-optimizer",
      "diagnostica-gargalos",
    ],
    filePath: "/.claude/agents/react-performance-optimizer.md",
  },
  {
    id: "social-media-clip-creator",
    name: "@social-media-clip-creator",
    category: "Frontend & UX",
    capabilities: "transforma conteúdo em clipes curtos e engajantes",
    usage:
      "divulgar releases internos para stakeholders via canais internos ou marketing.",
    example:
      "Ex.: gerar um carrossel interno explicando o rollout do `Workspace Launchpad` usando dados de `docs/content/releases/launchpad.mdx`.",
    shortExample: "`@social-media-clip-creator crie clip de release v2.0`",
    outputType:
      "Guia visual ou recomendações de UI/UX com referências de componentes.",
    tags: [
      "frontend",
      "ux",
      "social-media-clip-creator",
      "transforma-conteudo",
    ],
    filePath: "/.claude/agents/social-media-clip-creator.md",
  },
  {
    id: "typescript-pro",
    name: "@typescript-pro",
    category: "Frontend & UX",
    capabilities: "avançado em tipagem complexa, generics e segurança",
    usage:
      "reforçar contratos de tipos no dashboard e serviços compartilhados.",
    example:
      "Rodar ao reforçar tipos do store Zustand em `frontend/dashboard/src/store/serviceStatus.ts`, garantindo inferência correta.",
    shortExample: "`@typescript-pro crie tipos genéricos para API client`",
    outputType:
      "Guia visual ou recomendações de UI/UX com referências de componentes.",
    tags: ["frontend", "ux", "typescript-pro", "avancado-em", "generics-e"],
    filePath: "/.claude/agents/typescript-pro.md",
  },
  {
    id: "ui-ux-designer",
    name: "@ui-ux-designer",
    category: "Frontend & UX",
    capabilities: "define fluxos, wireframes e padrões de design",
    usage:
      "planejar jornadas de usuários traders, garantindo consistência visual e acessibilidade.",
    example:
      "Aplicar ao criar o fluxo de onboarding dos agentes no Figma e sincronizá-lo com a página `#/ai-agents-directory` do dashboard.",
    shortExample: "`@ui-ux-designer desenhe fluxo de execução de ordens`",
    outputType:
      "Guia visual ou recomendações de UI/UX com referências de componentes.",
    tags: ["frontend", "ux", "ui-ux-designer", "define-fluxos", "wireframes-e"],
    filePath: "/.claude/agents/ui-ux-designer.md",
  },
  {
    id: "data-analyst",
    name: "@data-analyst",
    category: "Dados & Analytics",
    capabilities: "analisa dados, monta dashboards e storytelling quantitativo",
    usage:
      "criar relatórios de performance de estratégias ou estudos de mercado usando TimescaleDB/QuestDB.",
    example:
      "Usar ao explorar métricas de execução em `data/warehouse/timescaledb/orders_summary.sql`, preparando insights para o comitê.",
    shortExample: "`@data-analyst analise performance de estratégias`",
    outputType:
      "Relatório analítico com métricas, tabelas e sugestões de visualização.",
    tags: [
      "dados",
      "analytics",
      "data-analyst",
      "analisa-dados",
      "monta-dashboards",
    ],
    filePath: "/.claude/agents/data-analyst.md",
  },
  {
    id: "data-engineer",
    name: "@data-engineer",
    category: "Dados & Analytics",
    capabilities: "orquestra pipelines, ETL e qualidade de dados",
    usage:
      "construir fluxos entre ProfitDLL, bancadas Timescale/Quest e os serviços de análise.",
    example:
      "Acionar quando orquestramos um pipeline incremental em `backend/data/pipelines/timescaledb-loader.ts` com agendamento systemd.",
    shortExample: "`@data-engineer crie pipeline ProfitDLL → TimescaleDB`",
    outputType:
      "Relatório analítico com métricas, tabelas e sugestões de visualização.",
    tags: [
      "dados",
      "analytics",
      "data-engineer",
      "orquestra-pipelines",
      "etl-e",
    ],
    filePath: "/.claude/agents/data-engineer.md",
  },
  {
    id: "data-scientist",
    name: "@data-scientist",
    category: "Dados & Analytics",
    capabilities: "experimenta modelos, features e validação estatística",
    usage: "testar novas abordagens de previsão ou detecção de sinais.",
    example:
      "Rodar ao validar features para o modelo de geração de sinais usando os notebooks em `notebooks/signal-lab.ipynb`.",
    shortExample: "`@data-scientist experimente modelo de previsão`",
    outputType:
      "Relatório analítico com métricas, tabelas e sugestões de visualização.",
    tags: [
      "dados",
      "analytics",
      "data-scientist",
      "experimenta-modelos",
      "features-e",
    ],
    filePath: "/.claude/agents/data-scientist.md",
  },
  {
    id: "database-admin",
    name: "@database-admin",
    category: "Dados & Analytics",
    capabilities: "gerencia instâncias, backup, tuning e segurança",
    usage:
      "operar TimescaleDB/QuestDB, planos de recuperação e gestão de permissões.",
    example:
      "Aplicar ao revisar planos de backup definidos em `tools/compose/docker-compose.db.yml` para TimescaleDB e QuestDB.",
    shortExample: "`@database-admin configure backup TimescaleDB`",
    outputType:
      "Relatório analítico com métricas, tabelas e sugestões de visualização.",
    tags: [
      "dados",
      "analytics",
      "database-admin",
      "gerencia-instancias",
      "backup",
    ],
    filePath: "/.claude/agents/database-admin.md",
  },
  {
    id: "database-architect",
    name: "@database-architect",
    category: "Dados & Analytics",
    capabilities:
      "modela esquemas, normaliza e define estratégias de indexação",
    usage:
      "desenhar novos domínios de dados de trading, coleções de RAG ou histórico de execuções.",
    example:
      "Usar quando desenhamos o esquema de posições persistido em `backend/data/timescaledb/schemas/positions.sql`, garantindo particionamento.",
    shortExample: "`@database-architect modele schema de trading`",
    outputType:
      "Relatório analítico com métricas, tabelas e sugestões de visualização.",
    tags: [
      "dados",
      "analytics",
      "database-architect",
      "modela-esquemas",
      "normaliza-e",
    ],
    filePath: "/.claude/agents/database-architect.md",
  },
  {
    id: "database-optimization",
    name: "@database-optimization",
    category: "Dados & Analytics",
    capabilities: "identifica queries e estruturas ineficientes",
    usage:
      "tunar consultas críticas de relatórios e operações de baixa latência.",
    example:
      "Ex.: rodar análises `EXPLAIN` dentro do script `backend/data/timescaledb/queries/latency.sql` propondo índices.",
    shortExample: "`@database-optimization tune query de relatórios`",
    outputType:
      "Relatório analítico com métricas, tabelas e sugestões de visualização.",
    tags: ["dados", "analytics", "database-optimization", "identifica-queries"],
    filePath: "/.claude/agents/database-optimization.md",
  },
  {
    id: "database-optimizer",
    name: "@database-optimizer",
    category: "Dados & Analytics",
    capabilities: "recomenda índices, particionamento e caching",
    usage: "otimizar fluxos de escrita/leitura de sinais e posições.",
    example:
      "Acionar ao inspecionar estatísticas de autovacuum registradas em `logs/db/timescale-autovacuum.log` e sugerir tuning.",
    shortExample: "`@database-optimizer recomende índices para signals`",
    outputType:
      "Relatório analítico com métricas, tabelas e sugestões de visualização.",
    tags: [
      "dados",
      "analytics",
      "database-optimizer",
      "recomenda-indices",
      "particionamento-e",
    ],
    filePath: "/.claude/agents/database-optimizer.md",
  },
  {
    id: "metadata-agent",
    name: "@metadata-agent",
    category: "Dados & Analytics",
    capabilities: "cria catálogos e padroniza metadados",
    usage:
      "manter inventário de bases (docs, coleções RAG, datasets de mercado) e rastrear upstream/downstream.",
    example:
      "Usar ao sincronizar arquivos `docs/content/reference/adrs/*.mdx` com o catálogo JSON `frontend/dashboard/src/data/aiAgentsDirectory.ts`.",
    shortExample: "`@metadata-agent catalogue coleções RAG`",
    outputType:
      "Relatório analítico com métricas, tabelas e sugestões de visualização.",
    tags: ["dados", "analytics", "metadata-agent", "cria-catalogos"],
    filePath: "/.claude/agents/metadata-agent.md",
  },
  {
    id: "nosql-specialist",
    name: "@nosql-specialist",
    category: "Dados & Analytics",
    capabilities: "desenha modelos em bancos NoSQL, sharding e consistência",
    usage: "apoiar uso de LowDB e eventuais stores chave-valor para caching.",
    example:
      "Aplicar ao normalizar coleções utilizadas no cache QuestDB em `backend/data/questdb/telemetry`, propondo modelos de eventos.",
    shortExample: "`@nosql-specialist desenhe modelo LowDB para cache`",
    outputType:
      "Relatório analítico com métricas, tabelas e sugestões de visualização.",
    tags: [
      "dados",
      "analytics",
      "nosql-specialist",
      "desenha-modelos",
      "sharding-e",
    ],
    filePath: "/.claude/agents/nosql-specialist.md",
  },
  {
    id: "sql-pro",
    name: "@sql-pro",
    category: "Dados & Analytics",
    capabilities: "domina SQL avançado, janelas e otimização",
    usage:
      "consultas analíticas em TimescaleDB, validação de materialized views e relatórios financeiros.",
    example:
      "Rodar ao revisar as CTEs do relatório `reports/daily/liquidity.sql` antes de liberar para o comitê de risco.",
    shortExample: "`@sql-pro crie window function para análise`",
    outputType:
      "Relatório analítico com métricas, tabelas e sugestões de visualização.",
    tags: ["dados", "analytics", "sql-pro", "domina-sql", "janelas-e"],
    filePath: "/.claude/agents/sql-pro.md",
  },
  {
    id: "ai-engineer",
    name: "@ai-engineer",
    category: "IA, ML & RAG",
    capabilities: "integra LLMs, pipelines RAG e orquestra agentes",
    usage:
      "evoluir `tools/rag-services`, connectors de LlamaIndex e fluxos de pesquisa documental.",
    example:
      "Usar quando conectamos um novo modelo Ollama para sumarizar diffs em `scripts/agents/docusaurus-daily.mjs`, ajustando prompts.",
    shortExample: "`@ai-engineer evolua pipeline LlamaIndex`",
    outputType:
      "Parecer técnico com métricas de modelo e próximos experimentos.",
    tags: ["ia", "ml", "rag", "ai-engineer", "integra-llms", "pipelines-rag"],
    filePath: "/.claude/agents/ai-engineer.md",
  },
  {
    id: "computer-vision-engineer",
    name: "@computer-vision-engineer",
    category: "IA, ML & RAG",
    capabilities: "visão computacional, detecção e OCR",
    usage:
      "processar relatórios visuais, notas de corretoras ou PDFs com gráficos.",
    example:
      "Ex.: calibrar o pipeline de OCR que lê prints do ProfitChart armazenados em `data/ingestion/screenshots/`.",
    shortExample: "`@computer-vision-engineer processe PDFs com gráficos`",
    outputType:
      "Parecer técnico com métricas de modelo e próximos experimentos.",
    tags: [
      "ia",
      "ml",
      "rag",
      "computer-vision-engineer",
      "visao-computacional",
      "deteccao-e",
    ],
    filePath: "/.claude/agents/computer-vision-engineer.md",
  },
  {
    id: "llms-maintainer",
    name: "@llms-maintainer",
    category: "IA, ML & RAG",
    capabilities: "mantém modelos grandes em produção, monitora custo e drift",
    usage:
      "governança dos modelos locais usados em agentes de documentação e análise.",
    example:
      "Aplicar ao atualizar o catálogo de modelos em `.claude/settings.json`, definindo fallback e limites de contexto.",
    shortExample: "`@llms-maintainer monitore modelo Ollama`",
    outputType:
      "Parecer técnico com métricas de modelo e próximos experimentos.",
    tags: [
      "ia",
      "ml",
      "rag",
      "llms-maintainer",
      "mantem-modelos",
      "monitora-custo",
    ],
    filePath: "/.claude/agents/llms-maintainer.md",
  },
  {
    id: "ml-engineer",
    name: "@ml-engineer",
    category: "IA, ML & RAG",
    capabilities: "operacionaliza modelos, feature stores e monitoramento",
    usage: "implantar modelos de previsão de mercado ou scoring de sinais.",
    example:
      "Rodar ao testar um classificador de tendência salvo em `models/order-signals/gradient_boosting.pkl`, garantindo métricas AUC.",
    shortExample: "`@ml-engineer implante modelo de previsão`",
    outputType:
      "Parecer técnico com métricas de modelo e próximos experimentos.",
    tags: [
      "ia",
      "ml",
      "rag",
      "ml-engineer",
      "operacionaliza-modelos",
      "feature-stores",
    ],
    filePath: "/.claude/agents/ml-engineer.md",
  },
  {
    id: "mlops-engineer",
    name: "@mlops-engineer",
    category: "IA, ML & RAG",
    capabilities: "CI/CD para modelos, versionamento e observabilidade",
    usage:
      "criar pipelines de treino/serving on-premise respeitando restrições de rede.",
    example:
      "Usar quando orquestramos o rollout do modelo acima via `tools/compose/mlops-stack.yml`, com versionamento em MLflow.",
    shortExample: "`@mlops-engineer crie pipeline treino on-premise`",
    outputType:
      "Parecer técnico com métricas de modelo e próximos experimentos.",
    tags: [
      "ia",
      "ml",
      "rag",
      "mlops-engineer",
      "ci-cd-para",
      "versionamento-e",
    ],
    filePath: "/.claude/agents/mlops-engineer.md",
  },
  {
    id: "model-evaluator",
    name: "@model-evaluator",
    category: "IA, ML & RAG",
    capabilities: "mede qualidade de modelos, benchmarks e fairness",
    usage: "comparar versões de modelos de risco ou pipelines RAG.",
    example:
      "Acionar ao comparar previsões de dois checkpoints dentro de `reports/model-eval/2025-11-05.md`, gerando tabela de métricas.",
    shortExample: "`@model-evaluator compare modelos de risco v1 vs v2`",
    outputType:
      "Parecer técnico com métricas de modelo e próximos experimentos.",
    tags: [
      "ia",
      "ml",
      "rag",
      "model-evaluator",
      "mede-qualidade",
      "benchmarks-e",
    ],
    filePath: "/.claude/agents/model-evaluator.md",
  },
  {
    id: "nlp-engineer",
    name: "@nlp-engineer",
    category: "IA, ML & RAG",
    capabilities: "NLP avançado, embeddings e interpretação",
    usage:
      "melhorar consultas naturais ao RAG e classificação de documentos textuais.",
    example:
      "Aplicar ao ajustar o pipeline de embeddings usado pelo RAG em `backend/api/workspace/src/services/search/embedding.ts`.",
    shortExample: "`@nlp-engineer melhore embeddings do RAG`",
    outputType:
      "Parecer técnico com métricas de modelo e próximos experimentos.",
    tags: ["ia", "ml", "rag", "nlp-engineer", "nlp-avancado", "embeddings-e"],
    filePath: "/.claude/agents/nlp-engineer.md",
  },
  {
    id: "ocr-grammar-fixer",
    name: "@ocr-grammar-fixer",
    category: "IA, ML & RAG",
    capabilities: "limpa erros linguísticos de OCR",
    usage:
      "pós-processar extratos convertidos de PDFs antes de alimentar o RAG.",
    example:
      "Usar após o OCR gerar markdown em `docs/content/ingestion/raw/`, limpando erros gramaticais antes da publicação.",
    shortExample: "`@ocr-grammar-fixer limpe texto extraído de PDF`",
    outputType:
      "Parecer técnico com métricas de modelo e próximos experimentos.",
    tags: ["ia", "ml", "rag", "ocr-grammar-fixer", "limpa-erros"],
    filePath: "/.claude/agents/ocr-grammar-fixer.md",
  },
  {
    id: "ocr-preprocessing-optimizer",
    name: "@ocr-preprocessing-optimizer",
    category: "IA, ML & RAG",
    capabilities: "prepara imagens para OCR com maior acurácia",
    usage: "otimizar ingestão de relatórios escaneados.",
    example:
      "Ex.: configurar filtros de ruído para as imagens armazenadas em `data/ingestion/raw-images/` antes do OCR principal.",
    shortExample: "`@ocr-preprocessing-optimizer otimize imagens escaneadas`",
    outputType:
      "Parecer técnico com métricas de modelo e próximos experimentos.",
    tags: ["ia", "ml", "rag", "ocr-preprocessing-optimizer", "prepara-imagens"],
    filePath: "/.claude/agents/ocr-preprocessing-optimizer.md",
  },
  {
    id: "ocr-quality-assurance",
    name: "@ocr-quality-assurance",
    category: "IA, ML & RAG",
    capabilities: "valida qualidade e cobertura de OCR",
    usage: "auditar pipelines de ingestão documental críticos.",
    example:
      "Rodar ao comparar PDFs processados com as versões em `docs/content/reports/daily/*.pdf`, garantindo aderência.",
    shortExample: "`@ocr-quality-assurance audite pipeline de ingestão`",
    outputType:
      "Parecer técnico com métricas de modelo e próximos experimentos.",
    tags: ["ia", "ml", "rag", "ocr-quality-assurance", "valida-qualidade"],
    filePath: "/.claude/agents/ocr-quality-assurance.md",
  },
  {
    id: "prompt-engineer",
    name: "@prompt-engineer",
    category: "IA, ML & RAG",
    capabilities: "projeta prompts robustos e cadeias de instruções",
    usage:
      "ajustar agentes (`scripts/agents`) e prompts do RAG para reduzir alucinações.",
    example:
      "Aplicar quando criamos o prompt de coaching para o agente `@workspace-launcher` documentado em `claude/commands/workspace-launcher.md`.",
    shortExample: "`@prompt-engineer ajuste prompts do RAG`",
    outputType:
      "Parecer técnico com métricas de modelo e próximos experimentos.",
    tags: ["ia", "ml", "rag", "prompt-engineer", "projeta-prompts"],
    filePath: "/.claude/agents/prompt-engineer.md",
  },
  {
    id: "quant-analyst",
    name: "@quant-analyst",
    category: "IA, ML & RAG",
    capabilities: "modelagem quantitativa, backtests e KPIs de trading",
    usage: "avaliar estratégias automatizadas, métricas de risco e retorno.",
    example:
      "Usar ao validar o backtest descrito em `reports/quant/backtest-2025-10-30.md`, conferindo métricas de Sharpe e drawdown.",
    shortExample: "`@quant-analyst avalie backtest de estratégia`",
    outputType:
      "Parecer técnico com métricas de modelo e próximos experimentos.",
    tags: [
      "ia",
      "ml",
      "rag",
      "quant-analyst",
      "modelagem-quantitativa",
      "backtests-e",
    ],
    filePath: "/.claude/agents/quant-analyst.md",
  },
  {
    id: "rag-analyzer",
    name: "@rag-analyzer",
    category: "IA, ML & RAG",
    capabilities: "audita pipelines RAG, embeddings e ranking",
    usage:
      "diagnosticar qualidade de busca em `tools/rag-services` e API documentation.",
    example:
      "Acionar ao investigar quedas de precisão no endpoint `/search/rag` observando índices em `backend/api/workspace/src/services/rag/index.ts`.",
    shortExample: "`@rag-analyzer diagnostique qualidade de busca`",
    outputType:
      "Parecer técnico com métricas de modelo e próximos experimentos.",
    tags: [
      "ia",
      "ml",
      "rag",
      "rag-analyzer",
      "audita-pipelines",
      "embeddings-e",
    ],
    filePath: "/.claude/agents/rag-analyzer.md",
  },
  {
    id: "search-specialist",
    name: "@search-specialist",
    category: "IA, ML & RAG",
    capabilities: "otimiza relevância de busca, sinônimos e ranking",
    usage: "calibrar indexação híbrida do dashboard e pipelines LlamaIndex.",
    example:
      "Aplicar ao tunar a relevância do search JSON armazenado em `frontend/dashboard/src/data/searchIndex.json`, ajustando boosts.",
    shortExample: "`@search-specialist calibre ranking LlamaIndex`",
    outputType:
      "Parecer técnico com métricas de modelo e próximos experimentos.",
    tags: [
      "ia",
      "ml",
      "rag",
      "search-specialist",
      "otimiza-relevancia",
      "sinonimos-e",
    ],
    filePath: "/.claude/agents/search-specialist.md",
  },
  {
    id: "visual-analysis-ocr",
    name: "@visual-analysis-ocr",
    category: "IA, ML & RAG",
    capabilities: "combina visão e OCR para interpretação de layouts",
    usage:
      "extrair informações estruturadas de relatórios financeiros complexos.",
    example:
      "Usar quando analisamos screenshots de ordens salvos em `data/visual-review/` para detectar divergências.",
    shortExample: "`@visual-analysis-ocr extraia dados de relatório`",
    outputType:
      "Parecer técnico com métricas de modelo e próximos experimentos.",
    tags: ["ia", "ml", "rag", "visual-analysis-ocr", "combina-visao"],
    filePath: "/.claude/agents/visual-analysis-ocr.md",
  },
  {
    id: "changelog-generator",
    name: "@changelog-generator",
    category: "Documentação & Conteúdo",
    capabilities: "sintetiza notas de versão a partir do histórico git",
    usage:
      "manter registros em `docs/REVIEW-INDEX*` ou relatórios de releases internos.",
    example:
      'Rodar ao preparar o post-mortem `CHANGELOG.md` da release, compilando commits de `git log --since="yesterday"`.',
    shortExample: "`@changelog-generator crie notas de versão v2.1`",
    outputType: "Documento Markdown estruturado com seções e links.",
    tags: [
      "documentacao",
      "conteudo",
      "changelog-generator",
      "sintetiza-notas",
    ],
    filePath: "/.claude/agents/changelog-generator.md",
  },
  {
    id: "connection-agent",
    name: "@connection-agent",
    category: "Documentação & Conteúdo",
    capabilities: "identifica ligações entre notas e reduz conteúdos órfãos",
    usage: "organizar vaults, relacionar ADRs e documentos de governança.",
    example:
      "Aplicar ao diagnosticar instabilidades reportadas em `logs/connections/workspace-link.log`, cruzando com alertas.",
    shortExample: "`@connection-agent relacione ADRs órfãos`",
    outputType: "Documento Markdown estruturado com seções e links.",
    tags: [
      "documentacao",
      "conteudo",
      "connection-agent",
      "identifica-ligacoes",
    ],
    filePath: "/.claude/agents/connection-agent.md",
  },
  {
    id: "content-curator",
    name: "@content-curator",
    category: "Documentação & Conteúdo",
    capabilities: "revisa qualidade de conteúdo e propõe melhorias",
    usage: "priorizar atualizações em `docs/content` e remover redundâncias.",
    example:
      "Usar quando precisamos reorganizar `docs/content/tools/security-config` para garantir narrativa coesa.",
    shortExample: "`@content-curator revise docs/content redundantes`",
    outputType: "Documento Markdown estruturado com seções e links.",
    tags: ["documentacao", "conteudo", "content-curator", "revisa-qualidade"],
    filePath: "/.claude/agents/content-curator.md",
  },
  {
    id: "context-manager",
    name: "@context-manager",
    category: "Documentação & Conteúdo",
    capabilities: "prepara pacotes de contexto precisos para agentes",
    usage:
      "alimentar automações com fragmentos relevantes de documentação e código.",
    example:
      "Ex.: preparar um pacote reduzido de arquivos para o agente principal antes de abrir `CLAUDE.md`, indicando caminhos críticos.",
    shortExample: "`@context-manager prepare contexto para agente`",
    outputType: "Documento Markdown estruturado com seções e links.",
    tags: ["documentacao", "conteudo", "context-manager", "prepara-pacotes"],
    filePath: "/.claude/agents/context-manager.md",
  },
  {
    id: "document-structure-analyzer",
    name: "@document-structure-analyzer",
    category: "Documentação & Conteúdo",
    capabilities: "verifica headings, TOC e hierarquias",
    usage:
      "garantir consistência das páginas Docusaurus e entregáveis executivos.",
    example:
      "Acionar ao validar se `docs/content/reference/adrs/ADR-018.mdx` segue heading hierarchy correta.",
    shortExample: "`@document-structure-analyzer verifique TOC Docusaurus`",
    outputType: "Documento Markdown estruturado com seções e links.",
    tags: [
      "documentacao",
      "conteudo",
      "document-structure-analyzer",
      "verifica-headings",
      "toc-e",
    ],
    filePath: "/.claude/agents/document-structure-analyzer.md",
  },
  {
    id: "documentation-expert",
    name: "@documentation-expert",
    category: "Documentação & Conteúdo",
    capabilities: "produz docs técnicas completas, guias e exemplos",
    usage: "escrever guias de APIs, setup local e padrões de contribuição.",
    example:
      "Aplicar quando escrevemos o tutorial `docs/content/how-to/connect-telegram.mdx` usando padrões de estilo do projeto.",
    shortExample: "`@documentation-expert escreva guia de setup local`",
    outputType: "Documento Markdown estruturado com seções e links.",
    tags: [
      "documentacao",
      "conteudo",
      "documentation-expert",
      "produz-docs",
      "guias-e",
    ],
    filePath: "/.claude/agents/documentation-expert.md",
  },
  {
    id: "docusaurus-expert",
    name: "@docusaurus-expert",
    category: "Documentação & Conteúdo",
    capabilities: "domina Docusaurus, plugins e build pipeline",
    usage:
      "personalizar o hub de documentação em `docs/` e resolver warnings de build.",
    example:
      "Usar ao debugar o build `npm run build` dentro de `docs`, ajustando `docusaurus.config.ts`.",
    shortExample: "`@docusaurus-expert resolva warnings de build`",
    outputType: "Documento Markdown estruturado com seções e links.",
    tags: [
      "documentacao",
      "conteudo",
      "docusaurus-expert",
      "domina-docusaurus",
      "plugins-e",
    ],
    filePath: "/.claude/agents/docusaurus-expert.md",
  },
  {
    id: "markdown-syntax-formatter",
    name: "@markdown-syntax-formatter",
    category: "Documentação & Conteúdo",
    capabilities: "normaliza sintaxe Markdown e lint",
    usage:
      "manter padrões nos relatórios em `docs/` e `outputs/` antes de publicar.",
    example:
      "Rodar ao limpar tabelas grandes em `docs/content/tools/trading/profitdll/assets-format.mdx`, garantindo sintaxe correta.",
    shortExample: "`@markdown-syntax-formatter normalize outputs/*.md`",
    outputType: "Documento Markdown estruturado com seções e links.",
    tags: [
      "documentacao",
      "conteudo",
      "markdown-syntax-formatter",
      "normaliza-sintaxe",
    ],
    filePath: "/.claude/agents/markdown-syntax-formatter.md",
  },
  {
    id: "moc-agent",
    name: "@moc-agent",
    category: "Documentação & Conteúdo",
    capabilities: "gera resumos e scripts de meeting of the minds (MoC)",
    usage: "registrar decisões de comitês técnicos ou retrospectivas.",
    example:
      "Ex.: sintetizar ata da reunião de integração usando as notas em `reports/meetings/moc-2025-11-05.md`.",
    shortExample: "`@moc-agent registre decisões de sprint review`",
    outputType: "Documento Markdown estruturado com seções e links.",
    tags: ["documentacao", "conteudo", "moc-agent", "gera-resumos"],
    filePath: "/.claude/agents/moc-agent.md",
  },
  {
    id: "report-generator",
    name: "@report-generator",
    category: "Documentação & Conteúdo",
    capabilities: "monta relatórios executivos, KPIs e gráficos narrativos",
    usage: "consolidar auditorias como `EXECUTIVE-SUMMARY` ou `NEXT-STEPS`.",
    example:
      "Aplicar ao montar o relatório diário em `docs/content/reports/daily/2025-11-05.mdx` a partir de logs de execução.",
    shortExample: "`@report-generator monte EXECUTIVE-SUMMARY`",
    outputType: "Documento Markdown estruturado com seções e links.",
    tags: [
      "documentacao",
      "conteudo",
      "report-generator",
      "monta-relatorios",
      "kpis-e",
    ],
    filePath: "/.claude/agents/report-generator.md",
  },
  {
    id: "technical-writer",
    name: "@technical-writer",
    category: "Documentação & Conteúdo",
    capabilities: "redige documentação técnica com clareza e consistência",
    usage: "padronizar manual de operação, ADRs e guias de segurança.",
    example:
      "Usar quando traduzimos decisões do ADR 020 em documentação acessível na wiki interna.",
    shortExample: "`@technical-writer padronize ADR template`",
    outputType: "Documento Markdown estruturado com seções e links.",
    tags: [
      "documentacao",
      "conteudo",
      "technical-writer",
      "redige-documentacao",
    ],
    filePath: "/.claude/agents/technical-writer.md",
  },
  {
    id: "vault-optimizer",
    name: "@vault-optimizer",
    category: "Documentação & Conteúdo",
    capabilities: "estrutura repositórios de conhecimento, taxonomias e tags",
    usage: "manter coerência entre `docs`, `AGENTS.md` e repositórios RAG.",
    example:
      "Acionar ao revisar a estrutura de `vault/secrets.hcl`, propondo políticas mais granulares.",
    shortExample: "`@vault-optimizer organize estrutura de docs`",
    outputType: "Documento Markdown estruturado com seções e links.",
    tags: [
      "documentacao",
      "conteudo",
      "vault-optimizer",
      "estrutura-repositorios",
      "taxonomias-e",
    ],
    filePath: "/.claude/agents/vault-optimizer.md",
  },
  {
    id: "academic-researcher",
    name: "@academic-researcher",
    category: "Pesquisa & Estratégia",
    capabilities: "pesquisa papers acadêmicos, revisões e citações",
    usage: "embasar estratégias quantitativas e requisitos regulatórios.",
    example:
      "Aplicar ao levantar baseline de papers para execução de ordens algorítmicas e registrar citações em `research/lit-review.md`.",
    shortExample: "`@academic-researcher pesquise papers sobre HFT`",
    outputType: "Brief executivo com referências e conclusões estratégicas.",
    tags: [
      "pesquisa",
      "estrategia",
      "academic-researcher",
      "pesquisa-papers",
      "revisoes-e",
    ],
    filePath: "/.claude/agents/academic-researcher.md",
  },
  {
    id: "competitive-intelligence-analyst",
    name: "@competitive-intelligence-analyst",
    category: "Pesquisa & Estratégia",
    capabilities: "monitora concorrentes e tendências",
    usage:
      "orientar roadmap diante de soluções de mercado ou novas regulações.",
    example:
      "Usar ao comparar soluções de trading rivais e registrar insights em `research/benchmarks/competitors.md`.",
    shortExample: "`@competitive-intelligence-analyst monitore regulações CVM`",
    outputType: "Brief executivo com referências e conclusões estratégicas.",
    tags: [
      "pesquisa",
      "estrategia",
      "competitive-intelligence-analyst",
      "monitora-concorrentes",
    ],
    filePath: "/.claude/agents/competitive-intelligence-analyst.md",
  },
  {
    id: "fact-checker",
    name: "@fact-checker",
    category: "Pesquisa & Estratégia",
    capabilities: "valida fatos, cifras e fontes",
    usage:
      "revisar relatórios e apresentações antes de stakeholders estratégicos.",
    example:
      "Acionar ao validar números publicados em `docs/content/reference/metrics/overview.mdx` contra fontes originais.",
    shortExample: "`@fact-checker valide métricas do relatório`",
    outputType: "Brief executivo com referências e conclusões estratégicas.",
    tags: [
      "pesquisa",
      "estrategia",
      "fact-checker",
      "valida-fatos",
      "cifras-e",
    ],
    filePath: "/.claude/agents/fact-checker.md",
  },
  {
    id: "hackathon-ai-strategist",
    name: "@hackathon-ai-strategist",
    category: "Pesquisa & Estratégia",
    capabilities: "estrutura planos para sprints de inovação ou hackathons",
    usage: "organizar blitz de evolução RAG/ML com squads multidisciplinares.",
    example:
      "Ex.: montar kit de desafios para hackathon interno descrevendo APIs reais em `docs/content/hackathons/2025Q1.md`.",
    shortExample: "`@hackathon-ai-strategist planeje sprint RAG`",
    outputType: "Brief executivo com referências e conclusões estratégicas.",
    tags: [
      "pesquisa",
      "estrategia",
      "hackathon-ai-strategist",
      "estrutura-planos",
    ],
    filePath: "/.claude/agents/hackathon-ai-strategist.md",
  },
  {
    id: "query-clarifier",
    name: "@query-clarifier",
    category: "Pesquisa & Estratégia",
    capabilities: "transforma pedidos vagos em briefs objetivos",
    usage:
      "alinhar requisitos de stakeholders antes de acionar agentes especialistas.",
    example:
      "Aplicar quando recebemos issue vaga no GitHub e precisamos transformar em briefing estruturado antes de enviar para outro agente.",
    shortExample: "`@query-clarifier transforme requisito vago em brief`",
    outputType: "Brief executivo com referências e conclusões estratégicas.",
    tags: ["pesquisa", "estrategia", "query-clarifier", "transforma-pedidos"],
    filePath: "/.claude/agents/query-clarifier.md",
  },
  {
    id: "research-brief-generator",
    name: "@research-brief-generator",
    category: "Pesquisa & Estratégia",
    capabilities: "gera briefs executivos a partir de pesquisas brutas",
    usage: "preparar sumários rápidos para diretoria ou comitês.",
    example:
      "Usar ao sintetizar descobertas sobre brokers em `research/notes/brokers.md` em um briefing executivo.",
    shortExample: "`@research-brief-generator gere sumário executivo`",
    outputType: "Brief executivo com referências e conclusões estratégicas.",
    tags: ["pesquisa", "estrategia", "research-brief-generator", "gera-briefs"],
    filePath: "/.claude/agents/research-brief-generator.md",
  },
  {
    id: "research-coordinator",
    name: "@research-coordinator",
    category: "Pesquisa & Estratégia",
    capabilities: "orquestra pesquisas distribuídas, agenda entregas",
    usage:
      "coordenar investigações simultâneas (ex. performance TP Capital + Docs Search).",
    example:
      "Rodar ao distribuir tarefas de investigação registradas em `research/kanban.md`, definindo responsáveis.",
    shortExample: "`@research-coordinator coordene estudos paralelos`",
    outputType: "Brief executivo com referências e conclusões estratégicas.",
    tags: [
      "pesquisa",
      "estrategia",
      "research-coordinator",
      "orquestra-pesquisas",
      "agenda-entregas",
    ],
    filePath: "/.claude/agents/research-coordinator.md",
  },
  {
    id: "research-orchestrator",
    name: "@research-orchestrator",
    category: "Pesquisa & Estratégia",
    capabilities: "divide temas complexos, distribui tarefas e integra achados",
    usage: "liderar estudos amplos como auditorias end-to-end de serviços.",
    example:
      "Aplicar quando precisamos combinar achados de múltiplos agentes e gerar plano consolidado em `research/orchestration.md`.",
    shortExample: "`@research-orchestrator lidere auditoria end-to-end`",
    outputType: "Brief executivo com referências e conclusões estratégicas.",
    tags: [
      "pesquisa",
      "estrategia",
      "research-orchestrator",
      "divide-temas",
      "distribui-tarefas",
    ],
    filePath: "/.claude/agents/research-orchestrator.md",
  },
  {
    id: "research-synthesizer",
    name: "@research-synthesizer",
    category: "Pesquisa & Estratégia",
    capabilities: "agrega múltiplas fontes em insights coesos",
    usage:
      "preparar decisões estratégicas baseadas em vários relatórios técnicos.",
    example:
      "Usar ao transformar 10 páginas de notas espalhadas em `research/raw/` em um sumário acionável.",
    shortExample: "`@research-synthesizer agregue relatórios técnicos`",
    outputType: "Brief executivo com referências e conclusões estratégicas.",
    tags: [
      "pesquisa",
      "estrategia",
      "research-synthesizer",
      "agrega-multiplas",
    ],
    filePath: "/.claude/agents/research-synthesizer.md",
  },
  {
    id: "technical-researcher",
    name: "@technical-researcher",
    category: "Pesquisa & Estratégia",
    capabilities: "investiga tecnologias emergentes e padrões técnicos",
    usage:
      "comparar arquiteturas event-driven, MCP ou soluções de data streaming.",
    example:
      "Acionar ao estudar protocolos FIX, extraindo trechos relevantes para `docs/content/integrations/fix/overview.mdx`.",
    shortExample: "`@technical-researcher compare arquiteturas event-driven`",
    outputType: "Brief executivo com referências e conclusões estratégicas.",
    tags: [
      "pesquisa",
      "estrategia",
      "technical-researcher",
      "investiga-tecnologias",
    ],
    filePath: "/.claude/agents/technical-researcher.md",
  },
  {
    id: "code-reviewer",
    name: "@code-reviewer",
    category: "QA & Observabilidade",
    capabilities: "conduz revisões de código focadas em qualidade e segurança",
    usage: "segunda validação antes de merges críticos.",
    example:
      "Aplicar ao revisar o PR que altera `frontend/dashboard/src/components/catalog/AgentsCatalogView.tsx`, focando bugs e padrões.",
    shortExample: "`@code-reviewer revise PR #123`",
    outputType: "Relatório de validação com achados, riscos e próximos testes.",
    tags: ["qa", "observabilidade", "code-reviewer", "conduz-revisoes"],
    filePath: "/.claude/agents/code-reviewer.md",
  },
  {
    id: "debugger",
    name: "@debugger",
    category: "QA & Observabilidade",
    capabilities: "diagnostica bugs complexos, race conditions e memória",
    usage: "desatar nós difíceis no backend Node ou scripts C/TypeScript.",
    example:
      "Usar ao reproduzir uma race condition em `backend/api/telegram-gateway/src/workers/updates.ts` com ajuda do inspector de Node.",
    shortExample: "`@debugger diagnostique race condition no WebSocket`",
    outputType: "Relatório de validação com achados, riscos e próximos testes.",
    tags: [
      "qa",
      "observabilidade",
      "debugger",
      "diagnostica-bugs",
      "race-conditions",
    ],
    filePath: "/.claude/agents/debugger.md",
  },
  {
    id: "error-detective",
    name: "@error-detective",
    category: "QA & Observabilidade",
    capabilities: "correlaciona logs, rastrea regressões e incidentes",
    usage: "analisar falhas reportadas em `outputs/workflow-*` ou Sentry.",
    example:
      "Acionar ao correlacionar alertas do Sentry com os logs em `logs/telegram-gateway/error.log`, identificando regressões.",
    shortExample: "`@error-detective correlacione logs do Sentry`",
    outputType: "Relatório de validação com achados, riscos e próximos testes.",
    tags: [
      "qa",
      "observabilidade",
      "error-detective",
      "correlaciona-logs",
      "rastrea-regressoes",
    ],
    filePath: "/.claude/agents/error-detective.md",
  },
  {
    id: "load-testing-specialist",
    name: "@load-testing-specialist",
    category: "QA & Observabilidade",
    capabilities: "planeja testes de carga e stress",
    usage: "simular volume de ordens, acessos simultâneos ao dashboard e APIs.",
    example:
      "Aplicar ao configurar cenários k6 em `tests/load/telegram-gateway.js` simulando 1000 ordens/seg.",
    shortExample: "`@load-testing-specialist simule 1000 ordens/segundo`",
    outputType: "Relatório de validação com achados, riscos e próximos testes.",
    tags: [
      "qa",
      "observabilidade",
      "load-testing-specialist",
      "planeja-testes",
    ],
    filePath: "/.claude/agents/load-testing-specialist.md",
  },
  {
    id: "performance-engineer",
    name: "@performance-engineer",
    category: "QA & Observabilidade",
    capabilities: "avalia KPIs, profiling e tuning de sistemas",
    usage: "medir latência das APIs e pipelines (TP Capital, RAG, docs).",
    example:
      "Usar ao medir p95 da API `/workspace/signals` monitorando `reports/perf/workspace-latency.json`.",
    shortExample: "`@performance-engineer meça latência TP Capital API`",
    outputType: "Relatório de validação com achados, riscos e próximos testes.",
    tags: [
      "qa",
      "observabilidade",
      "performance-engineer",
      "avalia-kpis",
      "profiling-e",
    ],
    filePath: "/.claude/agents/performance-engineer.md",
  },
  {
    id: "performance-profiler",
    name: "@performance-profiler",
    category: "QA & Observabilidade",
    capabilities: "instrumenta perfis detalhados de CPU/memória",
    usage:
      "investigar gargalos específicos em Node, scripts ML ou serviços dockerizados.",
    example:
      "Acionar ao capturar profile de CPU do serviço `documentation-api` usando `clinic flame` e armazenar em `reports/perf/flamegraphs/`.",
    shortExample: "`@performance-profiler profile Node.js memory leaks`",
    outputType: "Relatório de validação com achados, riscos e próximos testes.",
    tags: [
      "qa",
      "observabilidade",
      "performance-profiler",
      "instrumenta-perfis",
    ],
    filePath: "/.claude/agents/performance-profiler.md",
  },
  {
    id: "review-agent",
    name: "@review-agent",
    category: "QA & Observabilidade",
    capabilities: "visão holística de revisão (código, docs, processos)",
    usage: "auditorias finais antes de milestones de entrega.",
    example:
      "Aplicar antes de liberar a milestone registrada em `IMPLEMENTATION-COMPLETE.md`, cruzando código, docs e alertas.",
    shortExample: "`@review-agent audite milestone v2.0`",
    outputType: "Relatório de validação com achados, riscos e próximos testes.",
    tags: ["qa", "observabilidade", "review-agent", "visao-holistica", "docs"],
    filePath: "/.claude/agents/review-agent.md",
  },
  {
    id: "test-automator",
    name: "@test-automator",
    category: "QA & Observabilidade",
    capabilities: "escreve suites automatizadas, integra CI e mocks",
    usage: "ampliar cobertura Vitest/Vitest e testes backend Express.",
    example:
      "Usar ao expandir `frontend/dashboard/src/components/catalog/__tests__/AgentsCatalogView.test.tsx` cobrindo novos filtros.",
    shortExample: "`@test-automator amplie cobertura Vitest`",
    outputType: "Relatório de validação com achados, riscos e próximos testes.",
    tags: [
      "qa",
      "observabilidade",
      "test-automator",
      "escreve-suites",
      "integra-ci",
    ],
    filePath: "/.claude/agents/test-automator.md",
  },
  {
    id: "test-engineer",
    name: "@test-engineer",
    category: "QA & Observabilidade",
    capabilities: "planeja estratégias de teste, casos e QA manual",
    usage: "estruturar planos de regressão para releases importantes.",
    example:
      "Acionar ao montar o plano de regressão da release `2025.11` documentado em `TESTING.md`.",
    shortExample: "`@test-engineer estruture plano de regressão`",
    outputType: "Relatório de validação com achados, riscos e próximos testes.",
    tags: [
      "qa",
      "observabilidade",
      "test-engineer",
      "planeja-estrategias",
      "casos-e",
    ],
    filePath: "/.claude/agents/test-engineer.md",
  },
  {
    id: "text-comparison-validator",
    name: "@text-comparison-validator",
    category: "QA & Observabilidade",
    capabilities: "compara textos, detecta diffs significativos",
    usage: "validar respostas do RAG ou atualizações de documentação crítica.",
    example:
      "Aplicar ao comparar respostas antigas e novas do RAG salvando o diff em `reports/rag/comparisons.md`.",
    shortExample: "`@text-comparison-validator compare respostas RAG`",
    outputType: "Relatório de validação com achados, riscos e próximos testes.",
    tags: [
      "qa",
      "observabilidade",
      "text-comparison-validator",
      "compara-textos",
      "detecta-diffs",
    ],
    filePath: "/.claude/agents/text-comparison-validator.md",
  },
  {
    id: "timestamp-precision-specialist",
    name: "@timestamp-precision-specialist",
    category: "QA & Observabilidade",
    capabilities: "garante precisão de timestamps e sincronização",
    usage: "assegurar registros corretos para auditoria de ordens e eventos.",
    example:
      "Usar ao auditar logs de ordens em `logs/orders/stream.log`, conferindo sincronia com TimescaleDB.",
    shortExample: "`@timestamp-precision-specialist valide logs de auditoria`",
    outputType: "Relatório de validação com achados, riscos e próximos testes.",
    tags: [
      "qa",
      "observabilidade",
      "timestamp-precision-specialist",
      "garante-precisao",
    ],
    filePath: "/.claude/agents/timestamp-precision-specialist.md",
  },
  {
    id: "web-accessibility-checker",
    name: "@web-accessibility-checker",
    category: "QA & Observabilidade",
    capabilities: "audita acessibilidade (WCAG)",
    usage:
      "manter o dashboard e docs acessíveis para todos os perfis de usuário.",
    example:
      "Acionar ao rodar `npm run test:e2e:catalog:accessibility` e documentar achados no dashboard.",
    shortExample: "`@web-accessibility-checker audite WCAG dashboard`",
    outputType: "Relatório de validação com achados, riscos e próximos testes.",
    tags: [
      "qa",
      "observabilidade",
      "web-accessibility-checker",
      "audita-acessibilidade",
    ],
    filePath: "/.claude/agents/web-accessibility-checker.md",
  },
  {
    id: "web-vitals-optimizer",
    name: "@web-vitals-optimizer",
    category: "QA & Observabilidade",
    capabilities: "monitora Web Vitals e recomenda ajustes",
    usage:
      "controlar métricas de carregamento, interação e estabilidade visual.",
    example:
      "Usar ao investigar queda de CLS na rota `/#/catalog`, analisando `frontend/dashboard/playwright-report/web-vitals.html`.",
    shortExample: "`@web-vitals-optimizer monitore CLS do dashboard`",
    outputType: "Relatório de validação com achados, riscos e próximos testes.",
    tags: ["qa", "observabilidade", "web-vitals-optimizer", "monitora-web"],
    filePath: "/.claude/agents/web-vitals-optimizer.md",
  },
  {
    id: "agent-overview",
    name: "@agent-overview",
    category: "MCP & Automação",
    capabilities: "fornece visão geral das capacidades de agentes disponíveis",
    usage: "mapear rapidamente qual agente acionar numa sprint.",
    example:
      "Aplicar ao responder rapidamente qual agente cobre pipelines quando a squad abre issue no `/health-check all`.",
    shortExample: "`@agent-overview liste agentes para sprint atual`",
    outputType:
      "Especificação de comandos ou fluxos de automação passo a passo.",
    tags: ["mcp", "automacao", "agent-overview", "fornece-visao"],
    filePath: "/.claude/agents/agent-overview.md",
  },
  {
    id: "command-expert",
    name: "@command-expert",
    category: "MCP & Automação",
    capabilities: "projeta comandos CLI customizados",
    usage: "evoluir `claude/commands` e fluxos de automação.",
    example:
      "Usar para esboçar o comando `/service-launcher start workspace-api` dentro de `claude/commands/service-launcher.md`.",
    shortExample: "`@command-expert crie comando /health-check-full`",
    outputType:
      "Especificação de comandos ou fluxos de automação passo a passo.",
    tags: ["mcp", "automacao", "command-expert", "projeta-comandos"],
    filePath: "/.claude/agents/command-expert.md",
  },
  {
    id: "git-flow-manager",
    name: "@git-flow-manager",
    category: "MCP & Automação",
    capabilities: "padroniza fluxos git, convenções e branches",
    usage: "reforçar Conventional Commits e cadência de releases.",
    example:
      "Acionar ao definir a estratégia de release branch descrita em `WORKSPACE-STACK-IMPLEMENTATION-SUMMARY.md`.",
    shortExample: "`@git-flow-manager configure Conventional Commits`",
    outputType:
      "Especificação de comandos ou fluxos de automação passo a passo.",
    tags: [
      "mcp",
      "automacao",
      "git-flow-manager",
      "padroniza-fluxos",
      "convencoes-e",
    ],
    filePath: "/.claude/agents/git-flow-manager.md",
  },
  {
    id: "mcp-deployment-orchestrator",
    name: "@mcp-deployment-orchestrator",
    category: "MCP & Automação",
    capabilities: "implanta servidores MCP e gerencia ambientes",
    usage:
      "subir/atualizar servidores filesystem, docker, postgres integrados.",
    example:
      "Aplicar ao automatizar o rollout do servidor MCP filesystem descrito em `claude/mcp-servers.json`.",
    shortExample: "`@mcp-deployment-orchestrator suba servidor postgres`",
    outputType:
      "Especificação de comandos ou fluxos de automação passo a passo.",
    tags: [
      "mcp",
      "automacao",
      "mcp-deployment-orchestrator",
      "implanta-servidores",
    ],
    filePath: "/.claude/agents/mcp-deployment-orchestrator.md",
  },
  {
    id: "mcp-expert",
    name: "@mcp-expert",
    category: "MCP & Automação",
    capabilities: "consultoria ampla sobre uso de MCP",
    usage: "desenhar novas integrações e habilidades baseadas em MCP.",
    example:
      "Usar ao depurar integrações MCP customizadas na extensão Cline apontando para `config/mcp/servers.json`.",
    shortExample: "`@mcp-expert desenhe integração custom MCP`",
    outputType:
      "Especificação de comandos ou fluxos de automação passo a passo.",
    tags: ["mcp", "automacao", "mcp-expert", "consultoria-ampla"],
    filePath: "/.claude/agents/mcp-expert.md",
  },
  {
    id: "mcp-integration-engineer",
    name: "@mcp-integration-engineer",
    category: "MCP & Automação",
    capabilities: "integra MCP com apps existentes",
    usage:
      "conectar servidores MCP aos serviços Node/React e agentes personalizados.",
    example:
      "Acionar ao conectar o servidor Postgres MCP usando `${MCP_POSTGRES_URL}` e validar queries de catálogo.",
    shortExample: "`@mcp-integration-engineer conecte MCP ao dashboard`",
    outputType:
      "Especificação de comandos ou fluxos de automação passo a passo.",
    tags: ["mcp", "automacao", "mcp-integration-engineer", "integra-mcp"],
    filePath: "/.claude/agents/mcp-integration-engineer.md",
  },
  {
    id: "mcp-protocol-specialist",
    name: "@mcp-protocol-specialist",
    category: "MCP & Automação",
    capabilities: "garante aderência ao protocolo MCP e melhores práticas",
    usage: "revisar interações entre CLI, VSCode e servidores MCP.",
    example:
      "Aplicar ao revisar mensagens trocadas com agentes MCP no log `logs/mcp/server.log`, buscando violações de spec.",
    shortExample: "`@mcp-protocol-specialist revise interações VSCode`",
    outputType:
      "Especificação de comandos ou fluxos de automação passo a passo.",
    tags: ["mcp", "automacao", "mcp-protocol-specialist", "garante-aderencia"],
    filePath: "/.claude/agents/mcp-protocol-specialist.md",
  },
  {
    id: "mcp-registry-navigator",
    name: "@mcp-registry-navigator",
    category: "MCP & Automação",
    capabilities: "explora catálogos de servidores MCP disponíveis",
    usage:
      "descobrir plugins úteis para novos fluxos (por ex. monitoramento, segurança).",
    example:
      "Usar ao procurar servidores MCP prontos no registry e registrar shortlist em `tools/openspec/AGENTS.md`.",
    shortExample: "`@mcp-registry-navigator descubra plugins de monitoring`",
    outputType:
      "Especificação de comandos ou fluxos de automação passo a passo.",
    tags: ["mcp", "automacao", "mcp-registry-navigator", "explora-catalogos"],
    filePath: "/.claude/agents/mcp-registry-navigator.md",
  },
  {
    id: "mcp-security-auditor",
    name: "@mcp-security-auditor",
    category: "MCP & Automação",
    capabilities: "revisa segurança, credenciais e isolamento em MCP",
    usage:
      "assegurar que tokens (GitHub, Sentry, Postgres) estejam protegidos.",
    example:
      "Acionar ao auditar permissões do servidor filesystem remoto, cruzando `claude/MCP-FILESYSTEM-SETUP.md` com práticas de least privilege.",
    shortExample: "`@mcp-security-auditor audite tokens MCP`",
    outputType:
      "Especificação de comandos ou fluxos de automação passo a passo.",
    tags: [
      "mcp",
      "automacao",
      "mcp-security-auditor",
      "revisa-seguranca",
      "credenciais-e",
    ],
    filePath: "/.claude/agents/mcp-security-auditor.md",
  },
  {
    id: "mcp-server-architect",
    name: "@mcp-server-architect",
    category: "MCP & Automação",
    capabilities: "projeta arquitetura de servidores MCP custom",
    usage: "criar servidores sob medida para repositórios internos.",
    example:
      "Aplicar ao desenhar um servidor MCP sob medida para QuestDB, descrevendo fluxos em `design/mcp/questdb-server.md`.",
    shortExample: "`@mcp-server-architect projete servidor custom`",
    outputType:
      "Especificação de comandos ou fluxos de automação passo a passo.",
    tags: ["mcp", "automacao", "mcp-server-architect", "projeta-arquitetura"],
    filePath: "/.claude/agents/mcp-server-architect.md",
  },
  {
    id: "mcp-testing-engineer",
    name: "@mcp-testing-engineer",
    category: "MCP & Automação",
    capabilities: "cria suites de teste para servidores MCP",
    usage: "validar que comandos MCP funcionam antes de liberar para a equipe.",
    example:
      "Usar ao construir testes de contrato para MCP executando `claude/test-mcp-fs.sh` e anotando respostas.",
    shortExample: "`@mcp-testing-engineer teste servidor filesystem`",
    outputType:
      "Especificação de comandos ou fluxos de automação passo a passo.",
    tags: ["mcp", "automacao", "mcp-testing-engineer", "cria-suites"],
    filePath: "/.claude/agents/mcp-testing-engineer.md",
  },
  {
    id: "script-specialist",
    name: "@script-specialist",
    category: "MCP & Automação",
    capabilities: "escreve scripts de automação multi-plataforma",
    usage:
      "acelerar tarefas recorrentes em `scripts/maintenance` e `scripts/setup`.",
    example:
      "Acionar ao otimizar o script `scripts/agents/runner.mjs`, garantindo flags consistentes.",
    shortExample: "`@script-specialist crie script maintenance`",
    outputType:
      "Especificação de comandos ou fluxos de automação passo a passo.",
    tags: ["mcp", "automacao", "script-specialist", "escreve-scripts"],
    filePath: "/.claude/agents/script-specialist.md",
  },
  {
    id: "tag-agent",
    name: "@tag-agent",
    category: "MCP & Automação",
    capabilities: "propõe taxonomias e etiquetas funcionais",
    usage: "organizar tags em docs, issues e coleções RAG.",
    example:
      "Aplicar ao reclassificar tags dos agentes em `frontend/dashboard/src/data/aiAgentsDirectory.ts`, garantindo filtros úteis.",
    shortExample: "`@tag-agent organize taxonomia de docs`",
    outputType:
      "Especificação de comandos ou fluxos de automação passo a passo.",
    tags: ["mcp", "automacao", "tag-agent", "propoe-taxonomias"],
    filePath: "/.claude/agents/tag-agent.md",
  },
  {
    id: "task-decomposition-expert",
    name: "@task-decomposition-expert",
    category: "MCP & Automação",
    capabilities: "quebra problemas grandes em planos operacionais",
    usage: "planejar jornadas complexas (ex. audit + refactor + rollout).",
    example:
      "Usar ao quebrar o épico “Telemetry refactor” registrado em `WORKSPACE-STACK-IMPLEMENTATION-SUMMARY.md` em subtarefas acionáveis.",
    shortExample: "`@task-decomposition-expert quebre auditoria complexa`",
    outputType:
      "Especificação de comandos ou fluxos de automação passo a passo.",
    tags: ["mcp", "automacao", "task-decomposition-expert", "quebra-problemas"],
    filePath: "/.claude/agents/task-decomposition-expert.md",
  },
  {
    id: "url-context-validator",
    name: "@url-context-validator",
    category: "MCP & Automação",
    capabilities: "valida URLs, contexto e reputação",
    usage: "checar fontes externas antes de ingestão no RAG.",
    example:
      "Acionar ao validar se links adicionados a `docs/content/reference/adrs` respondem antes de enviar para outro agente.",
    shortExample: "`@url-context-validator valide URLs externas`",
    outputType:
      "Especificação de comandos ou fluxos de automação passo a passo.",
    tags: [
      "mcp",
      "automacao",
      "url-context-validator",
      "valida-urls",
      "contexto-e",
    ],
    filePath: "/.claude/agents/url-context-validator.md",
  },
  {
    id: "url-link-extractor",
    name: "@url-link-extractor",
    category: "MCP & Automação",
    capabilities: "extrai links estruturados e metadados",
    usage: "mapear dependências em documentos ou relatórios.",
    example:
      "Aplicar ao extrair todos os links da pasta `docs/content/tools/security-config` para revisão em massa.",
    shortExample: "`@url-link-extractor mapeie links de documento`",
    outputType:
      "Especificação de comandos ou fluxos de automação passo a passo.",
    tags: ["mcp", "automacao", "url-link-extractor", "extrai-links"],
    filePath: "/.claude/agents/url-link-extractor.md",
  },
];
