name: frontend-apps

services:
  frontend-apps-db:
    image: "${IMG_DATA_FRONTEND_APPS:-img-data-frontend-apps}:${IMG_VERSION:-2025.10.19}"
    container_name: data-frontend-apps
    platform: linux/amd64
    restart: unless-stopped
    env_file:
      - ../../.env
    environment:
      POSTGRES_DB: ${FRONTEND_APPS_DB_NAME:-frontend_apps}
      POSTGRES_USER: ${FRONTEND_APPS_DB_SUPERUSER:-frontend_admin}
      POSTGRES_PASSWORD: ${FRONTEND_APPS_DB_SUPERPASS:-change_me}
      TIMESCALEDB_TELEMETRY: 'off'
    ports:
      - '${FRONTEND_APPS_DB_PORT:-5444}:5432'
    volumes:
      - ../../data/frontend-apps:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${FRONTEND_APPS_DB_SUPERUSER:-frontend_admin} -d ${FRONTEND_APPS_DB_NAME:-frontend_apps}']
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - tradingsystem_data
    labels:
      - 'com.tradingsystem.stack=database'
      - 'com.tradingsystem.service=data-frontend-apps'
      - 'com.tradingsystem.description=Unified PostgreSQL server for frontend applications'

networks:
  tradingsystem_data:
    external: true
