# Image override file - referenced by start/stop scripts
# This keeps image repositories centralized via config/container-images.env
# while allowing local overrides through .env.local.

services:
  timescaledb:
    image: "${IMG_DATA_TIMESCALEDB}:${IMG_VERSION:-latest}"
  timescaledb-backup:
    image: "${IMG_DATA_TIMESCALEDB_BACKUP}:${IMG_VERSION:-latest}"
  timescaledb-exporter:
    image: "${IMG_DATA_TIMESCALEDB_EXPORTER}:${IMG_VERSION:-latest}"
  timescaledb-pgadmin:
    image: "${IMG_DATA_TIMESCALEDB_PGADMIN}:${IMG_VERSION:-latest}"
  timescaledb-pgweb:
    image: "${IMG_DATA_TIMESCALEDB_PGWEB}:${IMG_VERSION:-latest}"
  timescaledb-adminer:
    image: "${IMG_DATA_TIMESCALEDB_ADMINER}:${IMG_VERSION:-latest}"

  firecrawl-api:
    image: "${IMG_FIRECRAWL_API}:${IMG_VERSION:-latest}"
  firecrawl-postgres:
    image: "${IMG_FIRECRAWL_POSTGRES}:${IMG_VERSION:-latest}"
  firecrawl-redis:
    image: "${IMG_FIRECRAWL_REDIS}:${IMG_VERSION:-latest}"
  firecrawl-playwright:
    image: "${IMG_FIRECRAWL_PLAYWRIGHT}:${IMG_VERSION:-latest}"

  documentation-api:
    image: "${IMG_DOCS_API}:${IMG_VERSION:-latest}"

  qdrant:
    image: "${IMG_DATA_QDRANT}:${IMG_VERSION:-latest}"

  questdb:
    image: "${IMG_DATA_QUESTDB}:${IMG_VERSION:-latest}"
