name: tools

services:
  langgraph:
    image: "${IMG_TOOLS_LANGGRAPH:-img-infra-langgraph}:${IMG_VERSION:-latest}"
    container_name: tools-langgraph
    build:
      context: ../langgraph
      dockerfile: Dockerfile
    ports:
      - "${LANGGRAPH_PORT:-8111}:8111"
    restart: unless-stopped
    env_file:
      - ../../.env
    environment:
      - AGNO_API_URL=http://tools-agno-agents:8200
      - DOCS_API_URL=http://docs-api:80
      - FIRECRAWL_PROXY_URL=http://firecrawl-proxy:80
    networks:
      - tools_default
      - tradingsystem_backend

  llamaindex-ingestion:
    image: "${IMG_TOOLS_LLAMAINDEX_INGESTION:-img-tools-llamaindex-ingestion}:${IMG_VERSION:-latest}"
    container_name: tools-llamaindex-ingestion
    build:
      context: ../llamaindex
      dockerfile: Dockerfile.ingestion
    ports:
      - "${LLAMAINDEX_INGESTION_PORT:-8201}:8000"
    restart: unless-stopped
    env_file:
      - ../../.env
    environment:
      - QDRANT_HOST=${QDRANT_HOST:-data-qdrant}
      - QDRANT_PORT=${QDRANT_PORT:-6333}
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://ollama:11434}
      - OLLAMA_EMBED_MODEL=${OLLAMA_EMBEDDING_MODEL:-nomic-embed-text}
    networks:
      - tools_default
      - tradingsystem_backend

  llamaindex-query:
    image: "${IMG_TOOLS_LLAMAINDEX_QUERY:-img-tools-llamaindex-query}:${IMG_VERSION:-latest}"
    container_name: tools-llamaindex-query
    build:
      context: ../llamaindex
      dockerfile: Dockerfile.query
    ports:
      - "${LLAMAINDEX_QUERY_PORT:-8202}:8000"
    restart: unless-stopped
    env_file:
      - ../../.env
    environment:
      - QDRANT_HOST=${QDRANT_HOST:-data-qdrant}
      - QDRANT_PORT=${QDRANT_PORT:-6333}
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://ollama:11434}
      - OLLAMA_EMBED_MODEL=${OLLAMA_EMBEDDING_MODEL:-nomic-embed-text}
      - OLLAMA_MODEL=${OLLAMA_MODEL:-}
    networks:
      - tools_default
      - tradingsystem_backend

  agno-agents:
    image: "${IMG_TOOLS_AGNO_AGENTS:-img-infra-agno-agents}:${IMG_VERSION:-latest}"
    container_name: tools-agno-agents
    build:
      context: ../agno-agents
      dockerfile: Dockerfile
    ports:
      - "${AGNO_AGENTS_PORT:-8200}:8200"
    restart: unless-stopped
    env_file:
      - ../../.env
    networks:
      - tools_default
      - tradingsystem_backend

networks:
  tools_default:
    driver: bridge
  tradingsystem_backend:
    external: true
