name: monitoring

services:
  prometheus:
    image: "${IMG_MON_PROMETHEUS:-prom/prometheus}:${IMG_VERSION:-latest}"
    container_name: monitor-prometheus
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1'
    ports:
      - "${PROMETHEUS_PORT:-9090}:9090"
    restart: unless-stopped
    env_file:
      - ../../.env
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:9090/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  alertmanager:
    image: "${IMG_MON_ALERTMANAGER:-prom/alertmanager}:${IMG_VERSION:-latest}"
    container_name: monitor-alertmanager
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
    ports:
      - "${ALERTMANAGER_PORT:-9093}:9093"
    restart: unless-stopped
    env_file:
      - ../../.env
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:9093/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  grafana:
    image: "${IMG_MON_GRAFANA:-grafana/grafana}:${IMG_VERSION:-latest}"
    container_name: monitor-grafana
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
    ports:
      - "${GRAFANA_PORT:-3000}:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD:-admin}
    restart: unless-stopped
    env_file:
      - ../../.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  alert-router:
    image: "${IMG_MON_ALERT_ROUTER:-nginx}:${IMG_VERSION:-alpine}"
    container_name: monitor-alert-router
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
    ports:
      - "${ALERT_ROUTER_PORT:-9094}:80"
    restart: unless-stopped
    env_file:
      - ../../.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
