name: tools

services:
  langgraph:
    image: "${IMG_TOOLS_LANGGRAPH:-img-infra-langgraph}:${IMG_VERSION:-latest}"
    container_name: tools-langgraph
    build:
      context: ../langgraph
      dockerfile: Dockerfile
    ports:
      - "${LANGGRAPH_PORT:-8111}:8111"
    restart: unless-stopped
    env_file:
      - ../../.env
    environment:
      - AGNO_API_URL=http://tools-agno-agents:8200
      - DOCS_API_URL=http://docs-api:80
      - FIRECRAWL_PROXY_URL=http://firecrawl-proxy:80
    networks:
      - tools_default
      - tradingsystem_backend

  llamaindex-ingestion:
    image: "${IMG_TOOLS_LLAMAINDEX_INGESTION:-nginx}:${IMG_VERSION:-alpine}"
    container_name: tools-llamaindex-ingestion
    ports:
      - "${LLAMAINDEX_INGESTION_PORT:-8201}:80"
    restart: unless-stopped
    env_file:
      - ../../.env

  llamaindex-query:
    image: "${IMG_TOOLS_LLAMAINDEX_QUERY:-nginx}:${IMG_VERSION:-alpine}"
    container_name: tools-llamaindex-query
    ports:
      - "${LLAMAINDEX_QUERY_PORT:-8202}:80"
    restart: unless-stopped
    env_file:
      - ../../.env

  agno-agents:
    image: "${IMG_TOOLS_AGNO_AGENTS:-img-infra-agno-agents}:${IMG_VERSION:-latest}"
    container_name: tools-agno-agents
    build:
      context: ../agno-agents
      dockerfile: Dockerfile
    ports:
      - "${AGNO_AGENTS_PORT:-8200}:8200"
    restart: unless-stopped
    env_file:
      - ../../.env
    networks:
      - tools_default
      - tradingsystem_backend

networks:
  tools_default:
    driver: bridge
  tradingsystem_backend:
    external: true
