# LangGraph Alert Rules for Prometheus

groups:
  - name: langgraph_alerts
    interval: 30s
    rules:
      # Service Down
      - alert: LangGraphServiceDown
        expr: up{job="langgraph"} == 0
        for: 2m
        labels:
          severity: critical
          service: langgraph
        annotations:
          summary: "LangGraph service is down"
          description: "LangGraph service has been down for more than 2 minutes"

      # High Error Rate
      - alert: LangGraphHighErrorRate
        expr: |
          rate(langgraph_workflow_errors_total[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
          service: langgraph
        annotations:
          summary: "High error rate in LangGraph workflows"
          description: "LangGraph workflow error rate is {{ $value | humanizePercentage }} over the last 5 minutes"

      # Slow Workflow Execution
      - alert: LangGraphSlowWorkflows
        expr: |
          histogram_quantile(0.95, rate(langgraph_workflow_duration_seconds_bucket[5m])) > 30
        for: 10m
        labels:
          severity: warning
          service: langgraph
        annotations:
          summary: "LangGraph workflows are running slow"
          description: "95th percentile workflow duration is {{ $value }}s (threshold: 30s)"

      # High Memory Usage
      - alert: LangGraphHighMemory
        expr: |
          process_resident_memory_bytes{job="langgraph"} / 1024 / 1024 > 1000
        for: 5m
        labels:
          severity: warning
          service: langgraph
        annotations:
          summary: "LangGraph memory usage is high"
          description: "Memory usage is {{ $value | humanize }}MB (threshold: 1000MB)"

      # Database Connection Issues
      - alert: LangGraphDatabaseUnhealthy
        expr: |
          langgraph_dependency_status{dependency="postgres"} == 0
          or langgraph_dependency_status{dependency="questdb"} == 0
        for: 2m
        labels:
          severity: warning
          service: langgraph
        annotations:
          summary: "LangGraph database dependency is unhealthy"
          description: "Database {{ $labels.dependency }} is not responding"

      # Agno Agents Unavailable
      - alert: LangGraphAgnoUnavailable
        expr: |
          langgraph_dependency_status{dependency="agno_agents"} == 0
        for: 2m
        labels:
          severity: warning
          service: langgraph
        annotations:
          summary: "Agno Agents is unavailable"
          description: "LangGraph cannot communicate with Agno Agents service"

