apiVersion: apps/v1
kind: Deployment
metadata:
  name: nuq-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nuq-postgres
  template:
    metadata:
      labels:
        app: nuq-postgres
    spec:
      containers:
        - name: nuq-postgres
          image: ghcr.io/firecrawl/nuq-postgres:latest
          imagePullPolicy: Always
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_DB
              value: "postgres"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
      volumes:
        - name: postgres-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nuq-postgres
spec:
  selector:
    app: nuq-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
