#!/usr/bin/env bash
# Auto-generated by npm run ports:sync
# Do not edit manually.
set -euo pipefail

FAILURES=0
echo "🔍 Checking service health via localhost bindings"

echo -n "grafana (3000) ... "
STATUS=$(curl -s -o /dev/null -w "%{http_code}" "http://localhost:3000/login" || true)
if [ "$STATUS" = "200" ]; then
  echo "✅ healthy"
else
  echo "❌ unhealthy (expected 200, got ${STATUS:-n/a})"
  FAILURES=$((FAILURES + 1))
fi

echo -n "firecrawl-api (3002) ... "
STATUS=$(curl -s -o /dev/null -w "%{http_code}" "http://localhost:3002/" || true)
if [ "$STATUS" = "200" ]; then
  echo "✅ healthy"
else
  echo "❌ unhealthy (expected 200, got ${STATUS:-n/a})"
  FAILURES=$((FAILURES + 1))
fi

echo -n "documentation-legacy (3004) ... "
STATUS=$(curl -s -o /dev/null -w "%{http_code}" "http://localhost:3004/" || true)
if [ "$STATUS" = "200" ]; then
  echo "✅ healthy"
else
  echo "❌ unhealthy (expected 200, got ${STATUS:-n/a})"
  FAILURES=$((FAILURES + 1))
fi

echo -n "api-viewer (3101) ... "
STATUS=$(curl -s -o /dev/null -w "%{http_code}" "http://localhost:3101/" || true)
if [ "$STATUS" = "200" ]; then
  echo "✅ healthy"
else
  echo "❌ unhealthy (expected 200, got ${STATUS:-n/a})"
  FAILURES=$((FAILURES + 1))
fi

echo -n "dashboard (3103) ... "
STATUS=$(curl -s -o /dev/null -w "%{http_code}" "http://localhost:3103/" || true)
if [ "$STATUS" = "200" ]; then
  echo "✅ healthy"
else
  echo "❌ unhealthy (expected 200, got ${STATUS:-n/a})"
  FAILURES=$((FAILURES + 1))
fi

echo -n "workspace-api (3200) ... "
STATUS=$(curl -s -o /dev/null -w "%{http_code}" "http://localhost:3200/" || true)
if [ "$STATUS" = "200" ]; then
  echo "✅ healthy"
else
  echo "❌ unhealthy (expected 200, got ${STATUS:-n/a})"
  FAILURES=$((FAILURES + 1))
fi

echo -n "tp-capital-api (4008) ... "
STATUS=$(curl -s -o /dev/null -w "%{http_code}" "http://localhost:4008/health" || true)
if [ "$STATUS" = "200" ]; then
  echo "✅ healthy"
else
  echo "❌ unhealthy (expected 200, got ${STATUS:-n/a})"
  FAILURES=$((FAILURES + 1))
fi

echo -n "documentation-hub (3400) ... "
STATUS=$(curl -s -o /dev/null -w "%{http_code}" "http://localhost:3400/" || true)
if [ "$STATUS" = "200" ]; then
  echo "✅ healthy"
else
  echo "❌ unhealthy (expected 200, got ${STATUS:-n/a})"
  FAILURES=$((FAILURES + 1))
fi

echo -n "documentation-api (3401) ... "
STATUS=$(curl -s -o /dev/null -w "%{http_code}" "http://localhost:3401/health" || true)
if [ "$STATUS" = "200" ]; then
  echo "✅ healthy"
else
  echo "❌ unhealthy (expected 200, got ${STATUS:-n/a})"
  FAILURES=$((FAILURES + 1))
fi

echo -n "firecrawl-proxy (3600) ... "
STATUS=$(curl -s -o /dev/null -w "%{http_code}" "http://localhost:3600/" || true)
if [ "$STATUS" = "200" ]; then
  echo "✅ healthy"
else
  echo "❌ unhealthy (expected 200, got ${STATUS:-n/a})"
  FAILURES=$((FAILURES + 1))
fi

echo -n "n8n (3680) ... "
STATUS=$(curl -s -o /dev/null -w "%{http_code}" "http://localhost:3680/healthz" || true)
if [ "$STATUS" = "200" ]; then
  echo "✅ healthy"
else
  echo "❌ unhealthy (expected 200, got ${STATUS:-n/a})"
  FAILURES=$((FAILURES + 1))
fi

echo -n "telegram-mtproto (4007) ... "
STATUS=$(curl -s -o /dev/null -w "%{http_code}" "http://localhost:4007/health" || true)
if [ "$STATUS" = "200" ]; then
  echo "✅ healthy"
else
  echo "❌ unhealthy (expected 200, got ${STATUS:-n/a})"
  FAILURES=$((FAILURES + 1))
fi

echo -n "telegram-gateway-api (4010) ... "
STATUS=$(curl -s -o /dev/null -w "%{http_code}" "http://localhost:4010/health" || true)
if [ "$STATUS" = "200" ]; then
  echo "✅ healthy"
else
  echo "❌ unhealthy (expected 200, got ${STATUS:-n/a})"
  FAILURES=$((FAILURES + 1))
fi

echo -n "documentation-api-viewer (3102) ... "
STATUS=$(curl -s -o /dev/null -w "%{http_code}" "http://localhost:3102/" || true)
if [ "$STATUS" = "200" ]; then
  echo "✅ healthy"
else
  echo "❌ unhealthy (expected 200, got ${STATUS:-n/a})"
  FAILURES=$((FAILURES + 1))
fi

echo -n "telegram-rabbitmq-admin (15672) ... "
STATUS=$(curl -s -o /dev/null -w "%{http_code}" "http://localhost:15672/" || true)
if [ "$STATUS" = "200" ]; then
  echo "✅ healthy"
else
  echo "❌ unhealthy (expected 200, got ${STATUS:-n/a})"
  FAILURES=$((FAILURES + 1))
fi

echo -n "timescaledb-pgadmin (5050) ... "
STATUS=$(curl -s -o /dev/null -w "%{http_code}" "http://localhost:5050/" || true)
if [ "$STATUS" = "200" ]; then
  echo "✅ healthy"
else
  echo "❌ unhealthy (expected 200, got ${STATUS:-n/a})"
  FAILURES=$((FAILURES + 1))
fi

echo -n "timescaledb-pgweb (8081) ... "
STATUS=$(curl -s -o /dev/null -w "%{http_code}" "http://localhost:8081/" || true)
if [ "$STATUS" = "200" ]; then
  echo "✅ healthy"
else
  echo "❌ unhealthy (expected 200, got ${STATUS:-n/a})"
  FAILURES=$((FAILURES + 1))
fi

echo -n "timescaledb-exporter (9187) ... "
STATUS=$(curl -s -o /dev/null -w "%{http_code}" "http://localhost:9187/metrics" || true)
if [ "$STATUS" = "200" ]; then
  echo "✅ healthy"
else
  echo "❌ unhealthy (expected 200, got ${STATUS:-n/a})"
  FAILURES=$((FAILURES + 1))
fi

echo -n "questdb (9002) ... "
STATUS=$(curl -s -o /dev/null -w "%{http_code}" "http://localhost:9002/" || true)
if [ "$STATUS" = "200" ]; then
  echo "✅ healthy"
else
  echo "❌ unhealthy (expected 200, got ${STATUS:-n/a})"
  FAILURES=$((FAILURES + 1))
fi

echo -n "prometheus (9090) ... "
STATUS=$(curl -s -o /dev/null -w "%{http_code}" "http://localhost:9090/-/healthy" || true)
if [ "$STATUS" = "200" ]; then
  echo "✅ healthy"
else
  echo "❌ unhealthy (expected 200, got ${STATUS:-n/a})"
  FAILURES=$((FAILURES + 1))
fi

echo -n "alertmanager (9093) ... "
STATUS=$(curl -s -o /dev/null -w "%{http_code}" "http://localhost:9093/#/status" || true)
if [ "$STATUS" = "200" ]; then
  echo "✅ healthy"
else
  echo "❌ unhealthy (expected 200, got ${STATUS:-n/a})"
  FAILURES=$((FAILURES + 1))
fi

echo -n "qdrant (6333) ... "
STATUS=$(curl -s -o /dev/null -w "%{http_code}" "http://localhost:6333/healthz" || true)
if [ "$STATUS" = "200" ]; then
  echo "✅ healthy"
else
  echo "❌ unhealthy (expected 200, got ${STATUS:-n/a})"
  FAILURES=$((FAILURES + 1))
fi

echo -n "kestra-orchestrator (8180) ... "
STATUS=$(curl -s -o /dev/null -w "%{http_code}" "http://localhost:8180/actuator/health" || true)
if [ "$STATUS" = "200" ]; then
  echo "✅ healthy"
else
  echo "❌ unhealthy (expected 200, got ${STATUS:-n/a})"
  FAILURES=$((FAILURES + 1))
fi

echo -n "kestra-management (8685) ... "
STATUS=$(curl -s -o /dev/null -w "%{http_code}" "http://localhost:8685/actuator/health" || true)
if [ "$STATUS" = "200" ]; then
  echo "✅ healthy"
else
  echo "❌ unhealthy (expected 200, got ${STATUS:-n/a})"
  FAILURES=$((FAILURES + 1))
fi

if [ "$FAILURES" -gt 0 ]; then
  echo ""
  echo "❌ $FAILURES service(s) reported unhealthy status"
  exit 1
fi

echo ""
echo "✅ All services responded with expected status codes"