#!/bin/bash

################################################################################
# Example: Bugfix Workflow
#
# Purpose: Document a complete bugfix workflow including:
#          - Environment validation
#          - Code changes tracking
#          - Service health checks
#          - API validation
#          - Testing execution
#
# Usage:
#   bash scripts/workflows/examples/bugfix-workflow.sh "fix-name"
#
# Example:
#   bash scripts/workflows/examples/bugfix-workflow.sh "fix-search-results"
#
################################################################################

set -e

# Get bugfix name from argument
BUGFIX_NAME="${1:-unnamed-bugfix}"

# Navigate to project root
cd "$(dirname "$0")/../../.."

# Import generic template
source scripts/workflows/workflow-template.sh

# =============================================================================
# BUGFIX-SPECIFIC CONFIGURATION
# =============================================================================

WORKFLOW_NAME="${BUGFIX_NAME}"
WORKFLOW_TYPE="bugfix"

# Enable sections relevant to bugfix workflows
ENABLED_SECTIONS=(
    ["ENVIRONMENT_CHECK"]=true      # Always check environment
    ["SERVICE_HEALTH"]=true         # Verify services are running
    ["DATABASE_CHECK"]=false        # Usually not needed for frontend bugs
    ["API_VALIDATION"]=true         # Validate critical APIs
    ["CODE_CHANGES"]=true           # Document all modified files
    ["TESTING"]=true                # Run tests to verify fix
    ["PERFORMANCE_METRICS"]=false   # Not critical for bugfixes
    ["DOCUMENTATION"]=true          # Always document
)

# Services that should be running
SERVICES=(
    "dashboard:9080"
    "docs-hub:3400"
    "documentation-api:3401"
)

# Critical APIs to validate
declare -A API_ENDPOINTS=(
    ["Documentation API"]="http://localhost:3401/api/health"
    ["RAG Service"]="http://localhost:8201/health"
)

# Files modified in this bugfix (populate after making changes)
CODE_FILES=(
    # Add files here as you modify them
    # Example:
    # "frontend/dashboard/src/components/pages/DocsHybridSearchPage.tsx"
    # "tools/compose/docker-compose.4-4-rag-stack.yml"
)

# =============================================================================
# BUGFIX-SPECIFIC FUNCTIONS
# =============================================================================

# Custom validation for frontend bugs
validate_frontend_build() {
    log_info "Validating frontend build..."

    append_report "## Frontend Build Validation"
    append_report ""

    if [[ -d "frontend/dashboard" ]]; then
        cd frontend/dashboard

        # Check package.json exists
        if [[ ! -f "package.json" ]]; then
            log_error "package.json not found"
            append_report "❌ **Build Failed**: package.json not found"
            return 1
        fi

        # Run type check (faster than full build)
        append_report "### TypeScript Type Check"
        append_report '```bash'
        append_report "npx tsc --noEmit"
        if npx tsc --noEmit 2>&1 | tee -a "${REPORT_FILE}"; then
            append_report '```'
            append_report ""
            append_report "✅ **Type check passed**"
            log_success "TypeScript type check passed"
        else
            append_report '```'
            append_report ""
            append_report "❌ **Type check failed**"
            log_error "TypeScript type check failed"
        fi
        append_report ""

        cd ../..
    fi
}

# Validate bug is actually fixed
validate_bugfix() {
    log_info "Validating bugfix..."

    append_report "## Bugfix Validation"
    append_report ""

    # Add your specific validation steps here
    # Example:
    # 1. Check localStorage persistence
    # 2. Verify no 429 errors
    # 3. Confirm results don't disappear

    append_report "### Manual Validation Checklist"
    append_report ""
    append_report "- [ ] Bug reproduction steps no longer cause issue"
    append_report "- [ ] No console errors during testing"
    append_report "- [ ] No regression in other features"
    append_report "- [ ] Edge cases tested"
    append_report ""

    log_success "Bugfix validation checklist created"
}

# =============================================================================
# CUSTOM WORKFLOW EXECUTION
# =============================================================================

custom_main() {
    log_info "Starting bugfix workflow: ${BUGFIX_NAME}"

    # Initialize output directory
    init_output_dir

    # Create report header
    cat > "${REPORT_FILE}" <<EOF
# Bugfix Workflow Report: ${BUGFIX_NAME}

**Type**: Bugfix
**Date**: $(date '+%Y-%m-%d %H:%M:%S')
**Generated By**: bugfix-workflow.sh

---

EOF

    # Execute standard sections
    check_environment
    check_service_health
    validate_apis
    document_code_changes
    run_tests
    generate_documentation

    # Execute bugfix-specific validations
    validate_frontend_build
    validate_bugfix

    # Add completion footer
    append_report "---"
    append_report ""
    append_report "## Summary"
    append_report ""
    append_report "- **Status**: ✅ Workflow Completed"
    append_report "- **Duration**: ${SECONDS} seconds"
    append_report "- **Files Modified**: ${#CODE_FILES[@]}"
    append_report ""
    append_report "### Next Steps"
    append_report ""
    append_report "1. Review validation checklist above"
    append_report "2. Run manual tests in browser"
    append_report "3. Commit changes with conventional commit format"
    append_report "4. Create pull request with this report"
    append_report ""

    # Update index
    cat >> "${INDEX_FILE}" <<EOF
- [Bugfix Report](WORKFLOW-REPORT.md)

## Bugfix Summary

- **Name**: ${BUGFIX_NAME}
- **Status**: ✅ Completed
- **Duration**: ${SECONDS} seconds
- **Files Modified**: ${#CODE_FILES[@]}

## Validation

Review the [Bugfix Validation](WORKFLOW-REPORT.md#bugfix-validation) section for manual testing checklist.

## Quick Links

- [View Report](WORKFLOW-REPORT.md)
- [Modified Files](#code-changes)
- [Test Results](#test-results)

EOF

    log_success "Bugfix workflow complete!"
    log_info "Report: ${REPORT_FILE}"
    log_info "Index: ${INDEX_FILE}"
}

# =============================================================================
# EXECUTION
# =============================================================================

# Validate we're in project root
if [[ ! -f "CLAUDE.md" ]]; then
    log_error "Must be run from project root directory"
    exit 1
fi

# Run custom workflow
custom_main

exit 0
