apiVersion: v1
kind: Service
metadata:
  name: {{ include "firecrawl.fullname" . }}-playwright
spec:
  type: {{ .Values.service.playwright.type }}
  selector:
    app: {{ include "firecrawl.name" . }}-playwright
  ports:
    - protocol: TCP
      port: {{ .Values.service.playwright.port }}
      targetPort: {{ .Values.service.playwright.port }}
