apiVersion: v1
kind: Secret
metadata:
  name: {{ include "firecrawl.fullname" . }}-secret
type: Opaque
data:
  OPENAI_API_KEY: {{ .Values.secret.OPENAI_API_KEY | b64enc | quote }}
  SLACK_WEBHOOK_URL: {{ .Values.secret.SLACK_WEBHOOK_URL | b64enc | quote }}
  LLAMAPARSE_API_KEY: {{ .Values.secret.LLAMAPARSE_API_KEY | b64enc | quote }}
  BULL_AUTH_KEY: {{ .Values.secret.BULL_AUTH_KEY | b64enc | quote }}
  TEST_API_KEY: {{ .Values.secret.TEST_API_KEY | b64enc | quote }}
  POSTHOG_API_KEY: {{ .Values.secret.POSTHOG_API_KEY | b64enc | quote }}
  POSTHOG_HOST: {{ .Values.secret.POSTHOG_HOST | b64enc | quote }}
  SCRAPING_BEE_API_KEY: {{ .Values.secret.SCRAPING_BEE_API_KEY | b64enc | quote }}
  STRIPE_PRICE_ID_STANDARD: {{ .Values.secret.STRIPE_PRICE_ID_STANDARD | b64enc | quote }}
  STRIPE_PRICE_ID_SCALE: {{ .Values.secret.STRIPE_PRICE_ID_SCALE | b64enc | quote }}
  FIRE_ENGINE_BETA_URL: {{ .Values.secret.FIRE_ENGINE_BETA_URL | b64enc | quote }}
  REDIS_PASSWORD: {{ .Values.secret.REDIS_PASSWORD | b64enc | quote }}
