apiVersion: v1
kind: Service
metadata:
  name: {{ include "firecrawl.fullname" . }}-api
spec:
  type: {{ .Values.service.api.type }}
  selector:
    app: {{ include "firecrawl.name" . }}-api
  ports:
    - protocol: TCP
      port: {{ .Values.service.api.port }}
      targetPort: {{ .Values.service.api.port }}
