groups:
  - name: service_launcher_alerts
    interval: 30s
    rules:
      # Service Launcher down
      - alert: ServiceLauncherDown
        expr: up{job="service-launcher"} == 0
        for: 1m
        labels:
          severity: critical
          component: service-launcher
        annotations:
          summary: "Service Launcher is down"
          description: "Service Launcher API (port 3500) has been down for more than 1 minute"

      # Multiple services degraded
      - alert: MultipleServicesDegraded
        expr: service_launcher_overall_status < 1
        for: 5m
        labels:
          severity: warning
          component: service-launcher
        annotations:
          summary: "Multiple services are degraded"
          description: "Overall system status is {{ $value }} (1=ok, 0.5=degraded, 0=down)"

      # Multiple services down
      - alert: MultipleServicesDown
        expr: service_launcher_overall_status < 0.5
        for: 2m
        labels:
          severity: critical
          component: service-launcher
        annotations:
          summary: "Multiple services are down"
          description: "Overall system status is critical: {{ $value }}"

      # High health check latency
      - alert: HighHealthCheckLatency
        expr: |
          histogram_quantile(0.95,
            rate(service_launcher_health_check_duration_seconds_bucket[5m])
          ) > 1
        for: 10m
        labels:
          severity: warning
          component: service-launcher
        annotations:
          summary: "High health check latency detected"
          description: "95th percentile of health checks is {{ $value }}s (threshold: 1s)"

      # Circuit breaker open
      - alert: CircuitBreakerOpen
        expr: service_launcher_circuit_breaker_state > 0
        for: 2m
        labels:
          severity: warning
          component: service-launcher
        annotations:
          summary: "Circuit breaker open for service {{ $labels.service_id }}"
          description: "Service {{ $labels.service_id }} has circuit breaker open due to repeated failures"

      # Specific service down
      - alert: ServiceDown
        expr: service_launcher_service_status{service_id!="service-launcher"} == 0
        for: 5m
        labels:
          severity: warning
          component: service-launcher
        annotations:
          summary: "Service {{ $labels.service_name }} is down"
          description: "Service {{ $labels.service_name }} ({{ $labels.service_id }}) has been down for 5 minutes"

      # High failure rate
      - alert: HighServiceLaunchFailureRate
        expr: |
          rate(service_launcher_launch_total{status="failure"}[5m])
          /
          rate(service_launcher_launch_total[5m])
          > 0.5
        for: 5m
        labels:
          severity: warning
          component: service-launcher
        annotations:
          summary: "High service launch failure rate"
          description: "More than 50% of service launches are failing"













