name: Setup Python project
description: Configure Python runtime with dependency caching and optional installation.
inputs:
  python-version:
    description: Python version to install
    required: false
    default: '3.11'
  cache-dependency-path:
    description: Path to requirement/lock files for pip cache key
    required: false
  run-install:
    description: Whether to run the install command automatically
    required: false
    default: 'true'
  install-command:
    description: Command to install dependencies
    required: false
    default: pip install -r requirements.txt
  working-directory:
    description: Directory where install command should run
    required: false
    default: .

runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs['python-version'] }}
        cache: pip
        cache-dependency-path: ${{ inputs['cache-dependency-path'] }}

    - name: Install dependencies
      if: ${{ inputs['run-install'] == 'true' }}
      shell: bash
      working-directory: ${{ inputs['working-directory'] }}
      run: |
        set -euo pipefail
        ${{ inputs['install-command'] }}
