apiVersion: apps/v1
kind: Deployment
metadata:
  name: llamaindex-ingestion
  namespace: llamaindex-production
spec:
  replicas: 3  # More replicas for production
  selector:
    matchLabels:
      app: llamaindex-ingestion
  template:
    metadata:
      labels:
        app: llamaindex-ingestion
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - llamaindex-ingestion
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: ingestion
        image: ghcr.io/your-repo/llamaindex-ingestion:latest
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 9090
          name: metrics
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: llamaindex-secrets
              key: OPENAI_API_KEY
        envFrom:
        - configMapRef:
            name: llamaindex-config
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "2"
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}
      securityContext:
        fsGroup: 1000
      serviceAccountName: llamaindex-ingestion
---
apiVersion: v1
kind: Service
metadata:
  name: llamaindex-ingestion-service
  namespace: llamaindex-production
  labels:
    app: llamaindex-ingestion
spec:
  selector:
    app: llamaindex-ingestion
  ports:
  - name: http
    port: 8000
    targetPort: http
  - name: metrics
    port: 9090
    targetPort: metrics
  type: ClusterIP
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: llamaindex-ingestion-pdb
  namespace: llamaindex-production
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: llamaindex-ingestion
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: llamaindex-ingestion
  namespace: llamaindex-production
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: llamaindex-ingestion
  namespace: llamaindex-production
spec:
  selector:
    matchLabels:
      app: llamaindex-ingestion
  endpoints:
  - port: metrics
    interval: 30s