name: outros

services:
  registry:
    image: "${IMG_OUTROS_CONTAINERS_REGISTRY:-img-outros-containers-registry}:${IMG_VERSION:-2025.10.19}"
    container_name: outros-containers-registry
    platform: linux/amd64
    ports:
      - "5000:5000"
    volumes:
      - ./registry/config.yml:/etc/docker/registry/config.yml
      - registry-data:/var/lib/registry
    environment:
      REGISTRY_HTTP_ADDR: 0.0.0.0:5000
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5000/v2/_catalog"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    networks:
      - buildkit-net
    labels:
      - "com.tradingsystem.stack=outros"
      - "com.tradingsystem.service=outros-containers-registry"
      - "com.tradingsystem.description=Local registry for build cache"
  ollama:
    image: "${IMG_OLLAMA:-img-ollama}:${IMG_VERSION:-2025.10.19}"
    container_name: ollama
    restart: unless-stopped
    platform: linux/amd64
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    runtime: nvidia
    labels:
      - "com.tradingsystem.stack=outros"
      - "com.tradingsystem.service=ollama"
      - "com.tradingsystem.description=Local Ollama server"
networks:
  buildkit-net:
    name: buildkit-net
    external: true

volumes:
  registry-data:
  ollama-data:
  buildkit-data:
