import fs from 'fs/promises';
import { DEFAULTS } from '../lib/registry.js';

function buildHealthBlock(service) {
  const endpoint = service.healthcheck.endpoint || '/health';
  const expected = service.healthcheck.expected ?? 200;
  const scheme = service.protocol === 'https' ? 'https' : 'http';
  const url = `${scheme}://localhost:${service.port}${endpoint}`;

  return [
    `echo -n "${service.name} (${service.port}) ... "`,
    `STATUS=$(curl -s -o /dev/null -w "%{http_code}" "${url}" || true)`,
    `if [ "$STATUS" = "${expected}" ]; then`,
    '  echo "✅ healthy"',
    'else',
    `  echo "❌ unhealthy (expected ${expected}, got \${STATUS:-n/a})"`,
    '  FAILURES=$((FAILURES + 1))',
    'fi',
    '',
  ];
}

export async function generateHealthScript(registry, { targetPath = DEFAULTS.healthScriptPath } = {}) {
  const header = [
    '#!/usr/bin/env bash',
    '# Auto-generated by npm run ports:sync',
    '# Do not edit manually.',
    'set -euo pipefail',
    '',
    'FAILURES=0',
    'echo "🔍 Checking service health via localhost bindings"',
    '',
  ];

  const scriptLines = [...header];
  for (const service of registry.services) {
    if (!service.healthcheck) continue;
    scriptLines.push(...buildHealthBlock(service));
  }

  scriptLines.push(
    'if [ "$FAILURES" -gt 0 ]; then',
    '  echo ""',
    '  echo "❌ $FAILURES service(s) reported unhealthy status"',
    '  exit 1',
    'fi',
    '',
    'echo ""',
    'echo "✅ All services responded with expected status codes"',
  );

  await fs.writeFile(targetPath, scriptLines.join('\n'), 'utf8');
  await fs.chmod(targetPath, 0o755);
}
